samchon/nestia

README.md
Thank you for creating this awesome package!
I ran the command copied from the README.md and found that the `--out` tag is broken, so I updated the README.md.
(Sorry for letting the formatter modify the last line of this file, while I was editing directly on Github)
=> Fix: broken bash command in `README.md`

README.md
안녕하세요.
구경하다가 README의 NPM 링크를 클릭했는데 404 떠서 수정해봤습니다.
=> Fix: NPM url in `README.md`

package.json, src/index.ts
There had been someone trying SDK build without installing `nestia`.
Therefore, just make `nestia` can be build SDK library even when not installed.
=> Support build CLI even when not installed

packages/core/src/decorators/TypedBody.ts
use Express' `req.is` to verify MIME type to be `application/json`
=> Close #220 - use Express' `req.is` to verify MIME type to be `application/json`

package.json, packages/core/package.json, packages/core/src/executable/internal/FileRetriever.ts, src/internal/FileRetriever.ts
Exact `package.json` exploration logic when running `npx nestia setup` command.
=> Fix: exact `package.json` exploration logic

package.json, packages/core/package.json, packages/core/src/executable/internal/PluginConfigurator.ts, packages/core/src/programmers/TypedRouteProgrammer.ts, src/internal/PluginConfigurator.ts
```bash
npm run build
npm run test
```
=> Close #261 - `assertStringify()` became default

packages/sdk/package.json, packages/sdk/src/NestiaSdkApplication.ts
SDK and Swagger generator imported `ttypescript` without existence check.
Therefore, fixed the bug.
=> Check existence of `ttypescript` in SDK

packages/fetcher/package.json, packages/fetcher/src/Fetcher.ts
From now on, `DELETE` method can use request body.
Also, about `POST`, `PUT`, `PATCH` methods, they can omit the request body.
The new version of `@nestia/fetcher` is v1.0.1
=> Close #266 by accepting #247 - enhance Fetcher

packages/core/package.json, packages/core/src/decorators/EncryptedModule.ts, packages/core/src/decorators/EncryptedRoute.ts, packages/core/src/decorators/TypedRoute.ts, packages/core/src/decorators/internal/route_error.ts, packages/sdk/package.json
Succeeded to complicate dependency relationship of NestJS.
Therefore, restrict dependencies of NestJS through `peerDependencies`
=> Add `peerDependencies` in core and sdk

package.json, src/internal/PluginConfigurator.ts
`nest new <directory>` command of `@nestjs/cli` has changed to configures `strictNullChecks: false`.
In the past, it had configured `strict: false`.
Therefore, changed setup wizard of `typia` to consider `strictNullChecks` option, too.
=> Setup wizard to configure `strictNullChecks`

packages/sdk/package.json, packages/sdk/src/NestiaSdkApplication.ts, packages/sdk/src/analyses/ReflectAnalyzer.ts
There're some people that directly running script in controller files. In that case, when runs `npx nestia sdk` command, SDK generation would be halted without detailed error tracing (only `Error.message` would be shown).
Therefore, enhance `@nestia/sdk` to trace error from user defined controller, and report it detaily.
=> Trace error from user defined controller

.gitignore, packages/e2e/package.json, packages/e2e/src/DynamicExecutor.ts, packages/e2e/src/TestValidator.ts
`TestValidator` class had thrown `string` value instead of `Error` class typed instance. Also, `DynamicExecutor` could not handle such non `Error` typed exception.
```bash
npm run build
npm run test
```
=> Fix non-Error type bug of `@nestia/e2e`.

packages/core/package.json, packages/core/src/transform.ts, packages/sdk/package.json, packages/sdk/src/NestiaSdkApplication.ts, packages/sdk/src/analyses/ControllerAnalyzer.ts, packages/sdk/src/analyses/ImportAnalyzer.ts, packages/sdk/src/executable/internal/NestiaConfigCompilerOptions.ts, packages/sdk/src/executable/internal/NestiaSdkCommand.ts, packages/sdk/src/generates/SdkGenerator.ts, packages/sdk/src/structures/IRoute.ts, test/executable/start.js, test/features/distribute-assert/packages/api/package.json, test/features/distribute-json/packages/api/package.json, test/features/implicit-error/nestia.config.ts, test/features/implicit-error/src/Backend.ts, test/features/implicit-error/src/controllers/ImplicitController.ts, test/features/implicit-error/src/test/index.ts, test/features/implicit-error/swagger.json, test/features/implicit-error/tsconfig.json, test/features/non-strict-error/nestia.config.ts, test/features/non-strict-error/src/controllers/HealthController.ts, test/features/non-strict-error/tsconfig.json, test/features/non-strictNullChecks-but-strict-error/nestia.config.ts, test/features/non-strictNullChecks-but-strict-error/src/controllers/HealthController.ts, test/features/non-strictNullChecks-but-strict-error/tsconfig.json, test/features/non-strictNullChecks-error/nestia.config.ts, test/features/non-strictNullChecks-error/src/controllers/HealthController.ts, test/features/non-strictNullChecks-error/tsconfig.json, test/package.json
Too many `nestia` users are confusing by legacy projects that had configured `strictNullChecks: false`, and mis-report to my repo saying "nestia seems broken". 
I think it would better to entirely prohibit `strictNullChecks: false` option in compliation level. Therefore, since v4.0.4 update, `strictNullChecks: false` would be compilation error in every nestia utilizing projects.
Also, made SDK generator to prohibit implicit return in controller method without any type definition. It's because if SDK allows object literal expression without type definition, client developers utilizing the SDK library would be crazy due to they have to read backend server code.
=> Close #380 - prohibit non-strict option

packages/cli/package.json, packages/cli/src/NestiaStarter.ts
In CLI manual, there had been manager specification option, but had not supported for a long time.
Therefore, updated to support the `npx nestia start <directory> --manager <manager>` command.
=> Fix `npx nestia start <directory> --manager <manager>`

packages/cli/package.json, packages/cli/src/NestiaStarter.ts, packages/cli/src/index.ts
In Windows, `npx` command from non-installed (both local and global) package does not allow `--` argument. Therefore, configuring package manager in `npx nestia start <diretory> --manager yarn` command was not possible.
Therefore, prohibit the `--manager` argument and just enforce only to use `npm` package manager in the `npx nestia start <directory>` command. There's no way at now.
=> Prohibit manager arugment in `npx nestia start` command

README.md, packages/core/README.md, packages/core/package.json, packages/sdk/README.md, packages/sdk/package.json, test/package.json, website/pages/docs/index.mdx, website/pages/index.mdx
@kakasoo and @8471919 had contributed to enhance `Primitive` type. By the way, the new `Primitive` type requires at least TS 4.7.
Therefore, change `peerDependencies` config.
=> Upgrade peerDependencies of TypeScript

packages/cli/package.json, packages/cli/src/NestiaSetupWizard.ts
Some users are installing CLI as global mode like below:
- `npm install -g nestia`
If do like that, unable to utilize any other command like `npx nestia sdk` and `npx nestia swagger`. It is not what I've guided, but changed `npx nestia setup` to install `nestia` in local forcibly for them.
Therefore, from now on, weirdo users setting up `nestia` as global mode also can enjoy Nestia.
=> `npx nestia setup` to install CLI too.

packages/core/package.json, test/features/distribute-assert/packages/api/package.json, test/features/distribute-json/packages/api/package.json, test/package.json
`typia@4.0.12` has optimized validation by function inlining. Threfore, `@nestia/core` also follows the update.
=> Update typia version

packages/core/package.json, packages/e2e/package.json, packages/sdk/package.json, test/features/distribute-assert/packages/api/package.json, test/features/distribute-json/packages/api/package.json
Since `typia@4.1.1` update, Array like type no more considered as a real array type that iterating through `Array.forEach()` like functions. Instead, `typia@4.1.1` handles them through `Object.entries()` function.
Of course, the array like types are rarely used, and even I haven't seen it being used in field at all. However, as `typia@4.1.1` changed its validation rule of array like types, and as it is a basic change on the validation rule, `nestia` follows the update.
```typescript
// ARRAY LIKE TYPE
interface ArrayLike<T> {
length: number;
[n: number]: T;
}
// REAL ARRAY TYPE
type SomeNumberArray = number[];
```
=> Update typia version to 4.1.1

packages/sdk/package.json, packages/sdk/src/generates/SdkGenerator.ts, test/package.json
To support `verbatimModuleSyntax` option of `tsconfig.json`, I'd changed bundled files generated by `@nestia/sdk`, and replaced those files when running `npx nestia sdk` command.
By the way, there have been someone that modifying those bundled files for customizations. For them, I've complemented the SDK generator to update specific import statements suitable for `verbatimModuleSyntax`, to keep their customizations.
=> Complement #417 - update instead of replace

packages/core/package.json, packages/core/src/programmers/TypedQueryProgrammer.ts, test/features/distribute-assert/packages/api/package.json, test/features/distribute-json/packages/api/package.json, test/features/distribute/packages/api/package.json, test/package.json
When `@Query()` parameter decorator being used in NestJS, it would be always an empty object even when the parameter type is optional. It seems a typical type error, and `@TypedQuery` of `@nestia/core` generates a compile error in that case. By the way, the error message was not enough detailed, therefore it made `nestia` users confused.
Therefore, changed the compilation error message more reasonable.
=> Reasonable error message when optional query parameter begin used

benchmark/package.json, packages/core/package.json, packages/core/src/decorators/internal/TransformError.ts, packages/core/src/programmers/TypedParamProgrammer.ts, packages/core/src/programmers/TypedQueryProgrammer.ts, test/features/distribute-assert/packages/api/package.json, test/features/distribute-assert/swagger.json, test/features/distribute-json/packages/api/package.json, test/features/distribute-json/swagger.json, test/features/distribute/swagger.json, test/features/e2e/swagger.json, test/features/exception-filter/swagger.json, test/features/fastify/swagger.json, test/features/simulate/swagger.json, test/features/tags/swagger.json, test/package.json
When configured `exactOptionalPropertyTypes` property to be `true` in `tsconfig.json` file, predication logic of undefindable type from optional symbol (`?`) becomes different. By the way, I haven't known that and it was the reason `@nestia/core` could not detect undefindable type when the optional symbol `?` being used like below:
```typescript
interface IMember {
id: string;
age?: number; // considered as required when `exactOptionalPropertyTypes` being used
}
```
From now on (`v1.4.3`), `@nestia/core` can distinguish it.
=> Fix samchon/typia#706 - support `exactOptionalPropertyTypes`

packages/sdk/package.json, packages/sdk/src/generates/SwaggerGenerator.ts, packages/sdk/src/generates/internal/E2eFileProgrammer.ts
When running `npx nestia e2e` command, Nestia sometimes write unused import statements. 
Fixed that bug.
Also, fixed swagger generator bug that cannot escapse `toJSON()` function
=> Evolve e2e test functions and swagger generators

packages/migrate/assets/input/.gitignore, packages/migrate/package.json, packages/migrate/src/programmers/ControllerProgrammer.ts, packages/migrate/src/programmers/RouteProgrammer.ts, packages/migrate/src/programmers/SchemaProgrammer.ts, packages/migrate/src/structures/ISwaggeSchema.ts, packages/migrate/src/structures/ISwaggerRoute.ts, packages/migrate/src/utils/StringUtil.ts
When build `swagger.json` file from SpringDoc, it is not following the OpenAPI standard.
- Omits some essential properties
- Content-Type is a little bit weird (contains charset)
Therefore, fixed `@nestia/migrate` to even support the SpringDoc case.
=> Support non-standard swagger.json generated by SpringDoc

packages/sdk/package.json, packages/sdk/src/analyses/ControllerAnalyzer.ts, test/package.json
When error being detected when generating SDK or Swagger Documents, its message became a little bit detailed.
1. Location of file path became relative
2. Line and Column numbers are added
=> Enhance error message of SDK/swagger generator

packages/core/package.json, packages/core/src/programmers/TypedQueryProgrammer.ts, test/features/query/src/api/structures/IQuery.ts, test/features/query/src/test/features/api/test_api_query_nest.ts, test/features/query/swagger.json, test/package.json
In [fireblocks](https://www.fireblocks.com/) case, its swagger API has an optional typed Array in query parameter. It seems nonsensible, but it is actually used in that way.
- https://docs.fireblocks.com/api/v1/swagger.yaml
Therefore, allow optional typed Array in `@TypedQuery()`, and assign `undefined` value when the target property key never being used in the query string.
```typescript
export namespace IApiNftsOwnershipCollections {
export type GetQuery = {
/**
* Search owned collections. Possible criteria for search: collection name, collection contract address.
* 
*/
search?: string;
/**
* Page cursor to fetch
* 
*/
pageCursor?: string;
/**
* Items per page (max 100)
* 
* @minimum 1
* @maximum 100
*/
pageSize?: number;
/**
* Sort by param, it can be one param or a list of params …
```
=> Allow optional typed Array in `@TypedQuery()`

packages/core/src/programmers/TypedQueryProgrammer.ts, packages/migrate/assets/input/.gitignore, packages/migrate/assets/input/clickhouse.json, packages/migrate/assets/input/fireblocks.json, packages/migrate/assets/input/iamport.json, packages/migrate/package.json, packages/migrate/src/programmers/ControllerProgrammer.ts, packages/migrate/src/programmers/RouteProgrammer.ts, packages/migrate/src/structures/ISwaggerRoute.ts
Looking at clickhouse case, its path parameter names are not matched with their route path.
- route path: "/v1/organizations/:organizationId/services/:serviceId/backups"
- parameter name: "Organization ID"
Therefore, updated to use only binded parameter name of `route.path`.
=> Fix `@nestia/migrate` bug when weirdo path parameter name comes

packages/core/package.json, packages/core/src/decorators/TypedRoute.ts, packages/core/src/programmers/TypedHeadersProgrammer.ts, packages/e2e/package.json, packages/fetcher/package.json, packages/fetcher/src/IConnection.ts, packages/fetcher/src/IEncryptionPassword.ts, packages/sdk/package.json, packages/sdk/src/analyses/ReflectAnalyzer.ts, packages/sdk/src/structures/ISwaggerRoute.ts, test/features/distribute-assert/packages/api/package.json, test/features/distribute-assert/packages/api/tsconfig.json, test/features/encrypted/swagger.json, test/features/fastify/swagger.json, test/features/headers-decompose/src/api/structures/IHeaders.ts, test/features/headers-decompose/src/test/features/api/test_api_headers.ts, test/features/headers-decompose/swagger.json, test/features/headers/src/api/structures/IHeaders.ts, test/features/headers/src/test/features/api/test_api_headers.ts, test/features/headers/swagger.json, test/features/simulate/swagger.json, test/features/tags/src/api/functional/bbs/articles/index.ts, test/features/variable/src/api/functional/bbs/$package/articles/index.ts, test/package.json
Enhanced `IConnection.Headerify` type of `@nestia/fetcher` to be much stronger. It will validate special cases whether each property allows Array type or not through their key name. For example, "set-cookie" type must be Array type, and `Authorization` must be atomic type.
```typescript
export namespace IConnection {
export type Headerify<T extends object> = {
[P in keyof T]?: T[P] extends HeaderValue | undefined
? P extends string
? Lowercase<P> extends "set-cookie"
? T[P] extends Array<HeaderValue>
? T[P] | undefined
: never
: Lowercase<P> extends
| "age"
| "authorization"
| "content-length"
| "content-type"
| "etag"
| "expires"
| "from"
| "host"
| "if-modified-since"
| "if-unmodified-since"
| "last-modified"
| "location"
| "max-forwards"
| "proxy-authorization"
| "referer"
| …
```
=> Enhance #473 - `IConnection.Headerify` to be much stronger

packages/core/package.json, packages/fetcher/package.json, packages/fetcher/src/Fetcher.ts, packages/migrate/package.json, packages/sdk/package.json
I did a critical mistake on `typia@4.1.15`, and it will break your backend server. I've deprecated it, but for extremely unlucky case, I upped `typia`'s `peerDependencies` version to `4.1.16`.
=> Upgrade typia version to `1.4.16`

packages/core/package.json, packages/fetcher/package.json, packages/fetcher/src/Fetcher.ts, packages/sdk/package.json, test/features/distribute-assert/packages/api/package.json, test/features/distribute-json/packages/api/package.json, test/features/distribute/packages/api/package.json, test/package.json
When `@EncryptedRoute` defined controller method returns nothing (`void`), `@nestia/fetcher` had occured exception. Considering purpose of `@EncryptedRoute`, occuring exception from `@nestia/fetcher` can be considered as not a bug but a spec.
However, this is so unkind to users. Even though the exception is sensible to considering its principle, users may not think such deeply. So I've changed logic of `@nestia/fetcher` to support `void` return typed `@EncryptedRoute` method.
=> Enhance `@nestia/fetcher` for `@EncryptedRoute`

benchmark/package.json, deploy/latest.sh, deploy/next.sh, packages/core/package.json, packages/e2e/package.json, packages/fetcher/package.json, packages/migrate/package.json, packages/sdk/package.json, packages/sdk/src/generates/SwaggerGenerator.ts, packages/sdk/src/structures/ISwaggerRoute.ts, test/executable/start.js, test/features/distribute-assert/packages/api/package.json, test/features/distribute-json/packages/api/package.json, test/features/distribute/packages/api/package.json, test/features/exception-filter/swagger.json, test/features/fastify/swagger.json, test/features/headers/swagger.json, test/features/query/swagger.json, test/features/simulate/swagger.json, test/features/variable/swagger.json, test/package.json
Even when query parameter be defined just by one object type, it must have its specific name following the OpenAPI spec. 
Therefore, fix `@nestia/sdk` to always have parameter name, and the bug be fixed.
=> Fix #521 - swagger query parameter type must have specific name

packages/cli/package.json, packages/cli/src/NestiaSetupWizard.ts, packages/cli/src/internal/ArgumentParser.ts
Same with with samchon/typia#744
- Changed setup wizard
- Introduce not to support `yarn berry`
- Use `npm run postinstall` command instead
Unfortunately, `ts-patch` does not support `yarn berry`. Therefore, it is not possible to use transform mode of `typia` in the `yarn berry`. Therefore, to inform it and recommend not to use `yarn berry` in `typia`, I've changed setup wizard program. This change would be rolled back when `ts-patch` starts supporting the `yarn berry`.
Also, `yarn berry` does not support the `npm run prepare` command. I think this nonsensible story because the `npm run prepare` command is a standard feature of NPM, but this is the reality, so I can't help it. By the way, if `ts-patch` starts supporting `yarn berry`, configuring `npm run prepare` command by setup wizard …
=> Fix samchon/typia#744 - change setup wizard to deprecate yarn berry

benchmark/package.json, packages/cli/package.json, packages/core/package.json, packages/core/src/utils/ExceptionManager.ts, packages/fetcher/package.json, packages/migrate/assets/input/fireblocks.json, packages/migrate/package.json, packages/sdk/package.json, test/package.json, website/public/sitemap-0.xml
Very long time ago, `nestia` had designed to cast `typia.TypeGuardError` to `nest.BadRequestException` for request body validation. Such logic had to be deleted when `@nestia/core` be published, but had taken a mistake that forgetting the work.
Therefore, by this PR, I remove the logic.
=> Fix #489 - stop casting `typia.TypeGuardError` to 400 status code.

packages/cli/package.json, packages/cli/src/NestiaSetupWizard.ts, packages/core/package.json, packages/fetcher/package.json, packages/migrate/package.json, packages/sdk/package.json
`typia@v5` had been changed a lot with great enhancements. To adapt the new version of `typia` in `nestia`, `nestia` also needs major update.
By the way, there're many pending issues in here `nestia`. So, delay the update of `typia` for a while, and adapt it after making advances on `nestia`.
For example, `@nestia/fetcher` would be changed to support `Try<T, E>` mode, and do not perform extra import statement about AES encryption module.
=> Hold `typia@v5` update for a while

website/pages/docs/setup.mdx
In the setup.mdx , it said 
`When you want to set up nestia in exiting project ....` it should say 
`existing` rather than `exiting`
=> Fix(typo): Update setup.mdx

packages/sdk/src/generates/SwaggerGenerator.ts, packages/sdk/src/generates/internal/SwaggerSchemaGenerator.ts, packages/sdk/src/structures/ISwaggerLazyProperty.ts, packages/sdk/src/structures/ISwaggerLazySchema.ts, test/features/headers-decompose/swagger.json, test/features/query-decompose/swagger.json
When `decompose` option being used in swagger generator, comment tags written on property had been ignored.
```typescript
export interface IHeaders {
"x-category": "x" | "y" | "z";
"x-memo"?: string;
/**
* @default Samchon
*/
"x-name"?: string;
"x-values": number[];
"x-flags": boolean[];
/**
* @hidden
*/
"X-descriptions": string[];
}
```
=> Fix `decompose` option's bug on swagger generator with comment tags.

packages/core/package.json, packages/core/src/decorators/internal/route_error.ts, packages/fetcher/package.json, packages/sdk/package.json, test/features/distribute-assert/packages/api/package.json, test/features/distribute-json/packages/api/package.json, test/features/distribute/packages/api/package.json, test/package.json
`fastify@5` has depreacted `req.routePath` property like below. Therefore, changed  my code as `fastify` recommended.
```bash
(node:3756) [FSTDEP017] FastifyDeprecation: You are accessing the deprecated "request.routerPath" property. Use "request.routeOptions.url" instead. Property "req.routerPath" will be removed in `fastify@5`
```
=> Deprecated property of `faastify`.

packages/sdk/src/utils/SourceFinder.ts
- project's base path(rootDir) has string which matches to Glob Pattern(eg. [], *)
- generating swagger or sdk based on `input` paths of `nestia.config.ts`
My case, My base path is `~/dev/[project]inprogress/ProjectName`  
- sdk should find `.ts`files inside the paths of `input` of `nestia.config.ts`, analyze those `.ts` files and display the results to console properly.
- sdk finds the wrong files because it considers the string of the base path (matching the Globe pattern) to be a Globe pattern.
My case, It couldn't find any files.
- Make nestjs and nestia project inside `[test]nestia`
Replaced `path.resolve(pattern)` with `pattern` in `emplace` arrow function of `utils/SourceFinder.ts`
I think this change also serve its original purpose as before.
- `nestia.config.ts` is on root …
=> fix: resolved path might be pattern in glob

benchmark/package.json, packages/core/package.json, packages/e2e/package.json, packages/fetcher/package.json, packages/migrate/package.json, packages/sdk/package.json, packages/sdk/src/NestiaSdkApplication.ts, packages/sdk/src/analyses/ReflectAnalyzer.ts, test/features/clone-and-exact-optional-property/swagger.json, test/features/date/swagger.json, test/features/distribute-assert/packages/api/package.json, test/features/distribute-json/packages/api/package.json, test/features/distribute/packages/api/package.json, test/package.json
As current `@nestia/sdk`'s `ReflectAnalyzer` class had not checked whether exported member is class type or not, if user exports any atomic value in a controller class file, it became an error due to characteristics of `WeakSet`.
Therefore, fixed this bug just by adding a `typeof value === 'function` statement. Thanks to @Val0429 for such special case reporting.
```typescript
@Controller("something")
export class SomeController {}
export const SOME_ATOMIC_VALUE = 0;
```
https://github.com/samchon/nestia/blob/e995adcf0b78448ca53efe569bd37e9e25ead4a3/packages/sdk/src/analyses/ReflectAnalyzer.ts#L15-L39
=> Fix #631 - when non-class value being exported

benchmark/package.json, packages/cli/package.json, packages/cli/src/NestiaSetupWizard.ts, packages/core/package.json, packages/e2e/package.json, packages/fetcher/package.json, packages/migrate/package.json, packages/migrate/src/programmers/RouteProgrammer.ts, packages/migrate/src/structures/ISwaggerRoute.ts, packages/sdk/package.json, packages/sdk/src/generates/SdkGenerator.ts, packages/sdk/src/generates/internal/SdkDistributionComposer.ts, test/features/distribute-assert/packages/api/package.json, test/features/distribute-json/packages/api/package.json, test/features/distribute/packages/api/package.json, test/package.json, website/pages/docs/setup.mdx
To support `yarn berry` which had banned `npm prepare` script, I'd changed setup wizard of `nestia` to define `npm postinstall` script instead.
By the way, unlike the `npm prepare` script which works on only in the local drive and does not work when be installed from remote `npm`, `npm postinstall` script is working even when installing from the remote `npm`. Therefore, when publishing an `npm` module which has installed `tyipa` through setup wizard, it enforces users of derived libraries to run the `npm postinstall` command that requires `ts-patch` module.
To fix this crazy bug, I've decided to ban `yarn berry` on the setup wizard. From now on, when you run the `npx nestia setup` command, it will print a text that "yarn berry is not supported". If you still want to utilize the `yarn …
=> Ban `yarn berry` on setup manager.

packages/core/package.json, packages/fetcher/package.json, packages/sdk/package.json, packages/sdk/src/generates/SdkGenerator.ts, packages/sdk/src/generates/internal/SdkDistributionComposer.ts, test/package.json
I've banned `yarn berry` which does not support `npm prepare` command to change setup wizard to using the standard `npm prepare` command.
By the way, SDK distribution composer had determined whether the target distribution directory has been prepared by checking the `package.json` file with the `npm run prepare` command.
Therefore, if the SDK distrubition directory being composed by older version of `@nestia/sdk`, newer version's SDK distribution composer re-composed the distribution directory vulnerably.
This PR fixes such bug.
=> Complement #652 - fix bug of SDK distrubition composer.

packages/core/package.json, packages/fetcher/package.json, packages/sdk/package.json, test/package.json
I've mis-published `typia` dependency version.
It had to be `^5.2.2`, but had configured to `>=5.2.2 <6.0.0` like `peerDependencies` case.
=> Fix mis-published dependency info

packages/cli/package.json, packages/cli/src/NestiaStarter.ts, packages/cli/src/internal/CommandExecutor.ts, packages/sdk/src/executable/sdk.ts
When installing dependencies of `nestia` through the `npx nestia setup` command, the setup process can be failed by another libraries' `peerDependencies` restriction. By the way, as current nestia setup wizard does not print the console output during the dependencies' setup, user can't know the reason why of the setup failure.
Therefore, changed the setup wizard to print the console output during the dependencies' setup process.
=> Print CLI output when running `npx nestia setup`.

benchmark/package.json, packages/cli/package.json, packages/cli/src/NestiaSetupWizard.ts, packages/core/package.json, packages/e2e/package.json, packages/fetcher/package.json, packages/migrate/package.json, packages/sdk/package.json, test/features/distribute-assert/packages/api/package.json, test/features/distribute-json/packages/api/package.json, test/features/distribute/packages/api/package.json, test/package.json, website/pages/docs/sdk/sdk.mdx
As TypeScript v5.3 has break change on compiler API, current version of `ts-patch` does not work on the `typescript@5.3`.
Therefore, I've blocked the TypeScript v5.3 update by configuring `peedDependencies` of `package.json`.
This limitation would be resolved when `ts-patch` starts supporting the TypeScript v5.3 update.
- Related issue: https://github.com/nonara/ts-patch/issues/122
=> Pending TypeScript v5.3 update.

benchmark/package.json, packages/core/package.json, packages/e2e/package.json, packages/fetcher/package.json, packages/migrate/package.json, packages/sdk/package.json, packages/sdk/src/NestiaSdkApplication.ts, packages/sdk/src/analyses/ReflectAnalyzer.ts, packages/sdk/src/structures/IErrorReport.ts, packages/sdk/src/structures/INestiaProject.ts, test/features/distribute-assert/packages/api/package.json, test/features/distribute-json/packages/api/package.json, test/features/distribute/packages/api/package.json, test/package.json, website/pages/docs/sdk/sdk.mdx
When wildcase URL controller method exists, `@nestia/sdk` could't build it due to error from `path-to-regexp` library.
Therefore, decided to skip the wildcard controller method case.
```typescript
export class SomeController {
@All("*")
public someMethod() {...}
}
```
=> Ignore wildcard URL case.

benchmark/package.json, build/index.js, deploy/publish.js, packages/core/package.json, packages/e2e/package.json, packages/fetcher/package.json, packages/migrate/package.json, packages/sdk/package.json, packages/sdk/src/NestiaSdkApplication.ts, test/features/distribute-assert/packages/api/package.json, test/features/distribute-json/packages/api/package.json, test/features/distribute/packages/api/package.json, test/package.json, website/pages/docs/sdk/sdk.mdx
Since TypeScript v5.3 update, TypeScript compiler no more analyzes `JsDocComment` as default.
> The desire of that is to boosting up the compilation speed by not parsing the JS Doc Comments.
Therefore, to parepare the future TypeScript v5.3 release, I've updated `@nestia/sdk` to configure the `jsDocParsingMode` to parse every comments manually. For reference, the restriction of `peerDependencies` -> `"typescript": ">=4.8.0 <5.3.0"` would also be erased after formal TS v5.3 release.
https://github.com/microsoft/TypeScript/pull/55739
=> `ts.CompilerHost.jsDocParsingMode`

packages/core/package.json, packages/fetcher/package.json, packages/sdk/package.json, packages/sdk/src/analyses/GenericAnalyzer.ts, packages/sdk/src/analyses/ImportAnalyzer.ts, test/package.json
When invalid type being used in SDK or swagger generation, non-nullish coalesced codes had caused errors.
To fix it, make them to be safe through the nullish coalescing statements with `?` symbol.
=> Safe nullish coalescing for speical cases

packages/core/package.json, packages/core/src/decorators/TypedBody.ts, packages/fetcher/package.json, packages/sdk/package.json, test/package.json
In nowadays, I've added an option that configure `assertClone` to be `TypedBody()`'s validator. 
By the way, I've taken a mistake that have not considered the any typed property case from the request body DTO.
This PR fixes the problem, by supporting the `any` typed value cloning.
=> Fix samchon/typia#880 - `any` type comes when `assertClone` option.

benchmark/package.json, packages/core/package.json, packages/e2e/package.json, packages/fetcher/package.json, packages/migrate/package.json, packages/sdk/package.json, packages/sdk/src/generates/internal/SwaggerSchemaGenerator.ts, test/features/distribute-assert/packages/api/package.json, test/features/distribute-json/packages/api/package.json, test/features/distribute/packages/api/package.json, test/package.json, website/pages/docs/sdk/sdk.mdx
Since TypeScript v5.3 update, `tsc` no more parses `JSDocComment`s. Therefore, `typia` also cannot utilize those `JSDocComment` related features too, especially "Comment Tags" and "JSON schema generator".
To reflect such TypeScript v5.3 update, `typia` has newly added a  temporary CLI command `npx typia patch` that is hacking the TypeScript module to turning on the `JSDocComment` parsing. Also, `nestia` has adopted the CLI when running the `npx nestia setup` command.
- samchon/typia#883
- samchon/nestia#696
In today, `ts-patch` has started supporting the TypeScript v5.3 update by reading `package.json` of transformer libraries. Therefore, the temporary CLI command no more required. Following the `ts-patch` guide, this PR has configured the `package.json` file for `ts-patch`, and …
=> Adjust nonara/ts-patch#138

packages/migrate/package.json, packages/migrate/src/MigrateApplication.ts, packages/migrate/src/executable/bundle.ts, packages/migrate/src/internal/MigrateCommander.ts, packages/migrate/src/internal/MigrateInquirer.ts, packages/migrate/src/programmers/MigrateApiStartProgrammer.ts, packages/migrate/src/programmers/MigrateE2eFileProgrammer.ts, packages/migrate/src/programmers/MigrateE2eProgrammer.ts, packages/migrate/src/structures/IMigrateProgram.ts, packages/migrate/src/test/index.ts, website/pages/docs/migrate.mdx, website/public/sitemap-0.xml
From now on, `@nestia/migrate` generates e2e test functions, and it is for the next step development `@nestia/editor`.
=> Enhance `@nestia/migrate` to generate e2e test functions.

packages/migrate/package.json, packages/migrate/src/programmers/MigrateImportProgrammer.ts, packages/migrate/src/programmers/MigrateSchemaProgrammer.ts, packages/migrate/src/structures/ISwaggerComponents.ts
`ISwaggerComponents.namespace` property is for 3rd party application supporting.
=> Refactor `@nestia/migrate` for 3rd party application.

package.json, packages/core/package.json, packages/fetcher/package.json, packages/fetcher/src/EncryptedFetcher.ts, packages/fetcher/src/PlainFetcher.ts, packages/fetcher/src/internal/FetcherBase.ts, packages/sdk/package.json, test/package.json
Current `PlainFetcher` and `EncryptedFetcher` of `@nestia/fetcher` is wrapping return type to `Primitive` type.
By the way, actual return type of some controller method is complicate and the complicate type being exported to the SDK library, the `Primitive` type can make IDE slower.
This PR avoids such situation, by removing the `Primitive` type from both `PlainFetcher` and `EncryptedFetcher`.
=> Simplify `PlainFetcher` and `EncryptedFetcher`.

benchmark/package.json, package.json, packages/cli/package.json, packages/cli/src/NestiaSetupWizard.ts, packages/core/package.json, packages/e2e/package.json, packages/fetcher/package.json, packages/migrate/package.json, packages/sdk/package.json, test/features/distribute-assert-json/packages/api/package.json, test/features/distribute-assert/packages/api/package.json, test/features/distribute-json/packages/api/package.json, test/features/distribute/packages/api/package.json, test/package.json, website/package.json, website/pages/docs/sdk/sdk.mdx
As that issue is extremely rare case but critical when used in the SDK level, adjust and enforce latest version of `typia`.
=> Adjust samchon/typia#999: upgrade typia dependency

packages/e2e/src/DynamicExecutor.ts
in last version, nestia e2e wrapper can't use options.parameters function (but parameters function is required)
so, it is more good that wrapper function get options.parameters at 3rd function parameters.
=> feat: add wrapper parameters

package.json, packages/core/package.json, packages/fetcher/package.json, packages/fetcher/src/internal/FetcherBase.ts, packages/migrate/package.json, packages/sdk/package.json, test/features/app-globalPrefix/src/api/HttpError.ts, test/package.json
I'm making a cloud playground website that can import any library registered in the NPM registry with `esm.sh`.
By the way, as `esm.sh` has been published for `deno`, it is not possible to import `NodeJS` built-in libraries.
In such reason, this PR removes every direct import statements to the NodeJS built-in libraries, and performed indirect import through `import2` library, so that bundler cannot merge them.
=> Make compatible with https://esm.sh

packages/migrate/package.json, packages/migrate/src/programmers/MigrateSchemaProgrammer.ts, packages/migrate/src/structures/ISwaggerComponents.ts, website/package.json
It no more need from the 3rd party application, and even duplicated with `@nestia/sdk` and @nestia/migrate`.
=> Erase ISwaggerComponents["x-nestia-namespace"] property.

package.json, packages/core/README.md, packages/core/package.json, packages/core/src/decorators/TypedFormData.ts, packages/fetcher/README.md, packages/fetcher/package.json, packages/sdk/README.md, packages/sdk/package.json, test/features/multipart-form-data-fastify/src/api/structures/IMultipart.ts, test/features/multipart-form-data-fastify/src/test/features/api/test_api_multipart.ts, test/features/multipart-form-data-fastify/swagger.json, test/features/multipart-form-data/src/api/structures/IMultipart.ts, test/features/multipart-form-data/src/test/features/api/test_api_multipart.ts, test/features/multipart-form-data/swagger.json, test/package.json
When `@TypedFormData.Body()` being used with `fastify`, it could not compose non-binary properties.
It's because `@fastify/multipart` has totally different methodology, and I hadn't known it.
This PR fixes the bug, so that make non-binary properties to be propertly composed.
=> Fix #862: `@TypedFormData.Body()` in `fastify`.

package.json, packages/core/package.json, packages/core/src/decorators/internal/NoTransformConfigureError.ts, packages/fetcher/package.json, packages/sdk/package.json, test/package.json
Changed error message content, because the no transform configuration error also can be occured when running `npx nestia sdk` like command without type checking through `tsc`.
=> Fix #922: change no transform configuration error message.

benchmark/package.json, package.json, packages/benchmark/package.json, packages/core/package.json, packages/e2e/package.json, packages/fetcher/package.json, packages/migrate/package.json, packages/sdk/package.json, test/features/distribute-assert-json/packages/api/package.json, test/features/distribute-assert/packages/api/package.json, test/features/distribute-json/packages/api/package.json, test/features/distribute/packages/api/package.json, test/package.json
To support `@SwaggerExample()` in the type level - #954
=> Bump up `@samchon/openapi` version for `@SwaggerExample()`.

packages/sdk/assets/config/nestia.config.ts, website/pages/docs/sdk/e2e.mdx, website/pages/docs/sdk/sdk.mdx, website/pages/docs/sdk/simulator.mdx, website/pages/docs/sdk/swagger.mdx
`FastifyAdapter` is a valid export of @nestjs/platform-fastify, which is described as `FastifyAdaptor` in the comments of the template in nestia.config.ts, which is confusing for newbies, this PR fixes all the wrong exports and uses of `FastifyAdaptor`.
[https://docs.nestjs.com/techniques/performance](https://docs.nestjs.com/techniques/performance)
=> fix/docs: replace FastifyAdaptor with FastifyAdapter

packages/sdk/package.json, packages/sdk/src/executable/internal/NestiaConfigLoader.ts
Here is the issue: #966 
Running nestia sdk command with tsconfig compilerOption `jsx` cause the error below:
```
error TS5024: Compiler option 'jsx' requires a value of type string.
```
1. `nestia sdk` internally uses NestiaConfigLoader
2. NestiaConfigLoader's which uses `tsconfck.parseNative` to parse compilerOption from tsconfig (reference [here](https://github.com/samchon/nestia/blob/master/packages/sdk/src/executable/internal/NestiaConfigLoader.ts#L20))
3. `tsconfck.parseNative` uses typescript's native function, `readConfigFile` and `parseJsonConfigFileContent`
4. `parseJsonConfigFileContent` causes error - it resolves `jsx` to `number`, but `jsx` should be string!
5. ERROR
* Replace `tsconfck.parseNative` to `tsconfck.parse`
* Bump tsconfck to ^3.1.1
=> Fix #966: support `jsx` configured case.

package.json, packages/cli/package.json, packages/cli/src/internal/ArgumentParser.ts, packages/cli/src/internal/PluginConfigurator.ts, packages/core/package.json, packages/fetcher/package.json, packages/sdk/package.json, packages/sdk/src/NestiaSwaggerComposer.ts, packages/sdk/src/analyses/ConfigAnalyzer.ts, packages/sdk/src/analyses/ReflectControllerAnalyzer.ts, packages/sdk/src/analyses/ReflectHttpOperationAnalyzer.ts, packages/sdk/src/analyses/ReflectWebSocketOperationAnalyzer.ts, packages/sdk/src/generates/SwaggerGenerator.ts, packages/sdk/src/generates/internal/SwaggerOperationComposer.ts, packages/sdk/src/generates/internal/SwaggerOperationParameterComposer.ts, packages/sdk/src/module.ts, packages/sdk/src/utils/VersioningStrategy.ts, test/features/app/src/Backend.ts, test/features/app/src/executable/server.ts, test/features/app/src/test/features/test_runtime_swagger.ts, test/features/app/tsconfig.json, test/package.json
From now on, you can compose swagger documents in the runtime.
This is the way to do it.
```typescript
import { NestiaSwaggerComposer } from "@nestia/sdk";
import { INestApplication } from "@nestjs/common";
import { NestFactory } from "@nestjs/core";
import { SwaggerModule } from "@nestjs/swagger";
const bootstrap = async (): Promise<void> => {
const app: INestApplication = await NestFactory.create(ApplicationModule);
const document = await NestiaSwaggerComposer.document(app, {});
SwaggerModule.setup("api", app, document as any);
await app.listen(37_000);
};
bootstrap().catch(console.error);
```
```json
{
"compilerOptions": {
"strict": true,
"plugins": [
{ "transform": "typia/lib/transform" },
{ "transform": "@nestia/core/lib/transform" },
{ "transform": "@nestia/sdk/lib/transform" },
], …
```
=> Runtime swagger document composer.

website/pages/docs/setup.mdx
Updating the Nx documentation to try and help guide users trying to use Nestia and Nx.
=> Update Nx documentation

website/pages/docs/sdk/swagger.mdx
This pull request includes a minor update to the documentation in the `website/pages/docs/sdk/swagger.mdx` file. The change removes references to the OpenAI function calling schema in the command descriptions.
Documentation update:
* [`website/pages/docs/sdk/swagger.mdx`](diffhunk://#diff-eaca3d42c2f3f82134f28f4a6068a2b686a4521391149bba3a7993eb4ff02152L90-R98): Removed references to the OpenAI function calling schema in the command descriptions for building Swagger, SDK, and E2E test functions simultaneously.
=> Fix #1139: remove non-existing document link

.github/workflows/build.yml, benchmark/package.json, deploy/index.js, deploy/migrate.js, package.json, packages/benchmark/package.json, packages/core/package.json, packages/e2e/package.json, packages/editor/package.json, packages/fetcher/package.json, packages/migrate/package.json, packages/sdk/package.json
This pull request includes several updates and improvements across multiple files, focusing on dependency updates and refactoring the migration process. The most important changes include updating the `typia` dependency version, modifying the migration function to accept an object, and updating the version numbers of various packages.
Dependency updates:
* Updated `typia` dependency from version `7.1.0` to `7.2.0` in multiple `package.json` files. [[1]](diffhunk://#diff-ebd18337ce8dc8b96a8403d2731d05bbb7502293037672a62faa622e36d2821aL45-R45) [[2]](diffhunk://#diff-03d34ead8faa24fcf5b6d74b52eaf57db4400f375b60698e3f5024e28b29b0e1L37-R37) [[3]](diffhunk://#diff-0b810c38f3c138a3d5e44854edefd5eb966617ca84e62f06511f60acc40546c7L51-R60) …
=> Bump up `typia`, and `migrate`/`editor` follows the main version.

deploy/publish.js, package.json, packages/migrate/src/programmers/MigrateNestControllerProgrammer.ts, packages/migrate/src/programmers/MigrateNestMethodProgrammer.ts
This pull request includes several changes to the `packages/migrate` module and a version bump in the `package.json` file. The most important changes involve modifications to the `MigrateNestMethodProgrammer` and `MigrateNestControllerProgrammer` to support additional parameters and decorators.
Version update:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L4-R4): Updated the version from `4.5.0` to `4.5.1`.
Enhancements to `MigrateNestMethodProgrammer`:
* [`packages/migrate/src/programmers/MigrateNestMethodProgrammer.ts`](diffhunk://#diff-8384d1e88935787aa219fc2539e634e64f23c83b9cdfdae5f93e426ed89c1d86R19): Added `controller` parameter to the `write` function and `writeMethodDecorators` function to allow for more context when …
=> Fix `@nestia/migrate` bug and support `@HumanRoute()`

benchmark/package.json, package.json, packages/benchmark/package.json, packages/core/package.json, packages/core/src/decorators/TypedException.ts, packages/e2e/package.json, packages/editor/package.json, packages/fetcher/package.json, packages/migrate/package.json, packages/sdk/package.json, test/features/exception/src/controllers/ExceptionController.ts, test/features/exception/src/test/features/test_swagger.ts, test/features/exception/swagger.json
This pull request includes several updates to version dependencies and enhancements to the `TypedException` decorator. The most important changes include version bumps for various packages and the addition of detailed properties and examples to the `TypedException` decorator.
* Updated `typia` dependency version from `^7.5.0` to `^7.5.1` in multiple `package.json` files. [[1]](diffhunk://#diff-ebd18337ce8dc8b96a8403d2731d05bbb7502293037672a62faa622e36d2821aL45-R45) [[2]](diffhunk://#diff-03d34ead8faa24fcf5b6d74b52eaf57db4400f375b60698e3f5024e28b29b0e1L37-R37) [[3]](diffhunk://#diff-0b810c38f3c138a3d5e44854edefd5eb966617ca84e62f06511f60acc40546c7L51-R51) [[4]](diffhunk://#diff-67adead8de9872bd465961c6570bce9bc06e7164ea116e45ad405ddf8eff238aL44-R44) …
=> Fix `TypedException.IProps.examples` type.

.github/workflows/build.yml, .github/workflows/migrate.yaml, .github/workflows/release.yml, .github/workflows/website.yml
Related to https://github.com/samchon/typia/pull/1414
- use `lts` instead of node20
- use matrix for use multiple node version for test
=> fix(ci): use `lts/*` instead of 20.x

benchmark/package.json, package.json, packages/agent/package.json, packages/benchmark/package.json, packages/chat/package.json, packages/core/package.json, packages/e2e/package.json, packages/editor/package.json, packages/fetcher/package.json, packages/migrate/package.json, packages/sdk/package.json, test/package.json
This pull request includes various updates to package versions across multiple files. The most significant changes involve updating the versions of `typia` and `@samchon/openapi` dependencies, as well as incrementing the version numbers of several packages.
* Updated `typia` dependency from `^7.5.1` to `^7.6.0` across multiple `package.json` files. [[1]](diffhunk://#diff-ebd18337ce8dc8b96a8403d2731d05bbb7502293037672a62faa622e36d2821aL45-R45) [[2]](diffhunk://#diff-03d34ead8faa24fcf5b6d74b52eaf57db4400f375b60698e3f5024e28b29b0e1L37-R37) [[3]](diffhunk://#diff-0b810c38f3c138a3d5e44854edefd5eb966617ca84e62f06511f60acc40546c7L51-R51) [[4]](diffhunk://#diff-0b810c38f3c138a3d5e44854edefd5eb966617ca84e62f06511f60acc40546c7L60-R60) [[5]](diffhunk://#diff-67adead8de9872bd465961c6570bce9bc06e7164ea …
=> Bump up dependencies: `@samchon/openapi` and `typia`.

packages/chat/package.json, packages/chat/src/movies/NestiaChatMovie.tsx, packages/chat/src/movies/messages/NestiaChatDescribeMessageMovie.tsx, packages/chat/src/movies/messages/NestiaChatSelectMessageMovie.tsx, packages/chat/src/movies/messages/NestiaChatTextMessageMovie.tsx
This pull request includes several changes to the `NestiaChatMovie` component and related files to improve code organization, add new features, and enhance the user interface. The most important changes include the addition of new icons and UI elements, refactoring of event listeners, and updates to the layout for better responsiveness.
* Refactored event listeners in `NestiaChatMovie` to improve readability and maintainability by separating initialization, event interactions, and event handlers. [[1]](diffhunk://#diff-303585d6dace2eb857977db184d2017458cd534e4ece338395ea3877270e3adfR57-R71) [[2]](diffhunk://#diff-303585d6dace2eb857977db184d2017458cd534e4ece338395ea3877270e3adfL77-R107)
* Added comments and organized code into sections such as variables, states, event interactions, …
=> Make `@nestia/agent` responsive.

website/pages/_meta.js, website/pages/playground/index.mdx
This pull request includes changes to enhance the `playground` section of the website. The main updates involve converting the `playground` type from a page to a menu and removing the automatic redirection from the `playground` index page.
Changes to `playground` section:
* [`website/pages/_meta.js`](diffhunk://#diff-54bc2d530749150030c3c846b56e6da49ed548e3523d5462ad8bd32ca608958dL16-R33): Changed the `playground` type from "page" to "menu" and added items for "Boilerplate", "WebSocket", and "A.I. Chatbot" with respective links that open in new windows.
* [`website/pages/playground/index.mdx`](diffhunk://#diff-98582dc10291b458365ec490c3f30d89034331e2ca84b5ae8d6203c77cc1e34aL1-L4): Removed the meta tag that automatically redirected the page to the "Boilerplate" link.
=> Website playground button as menu

website/pages/docs/core/TypedBody.mdx, website/pages/docs/core/TypedException.mdx, website/pages/docs/core/TypedFormData.mdx, website/pages/docs/core/TypedHeaders.mdx, website/pages/docs/core/TypedParam.mdx, website/pages/docs/core/TypedQuery.mdx, website/pages/docs/core/TypedRoute.mdx, website/pages/docs/core/WebSocketRoute.mdx, website/pages/docs/e2e/benchmark.mdx, website/pages/docs/e2e/development.mdx, website/pages/docs/e2e/why.mdx, website/pages/docs/editor.mdx, website/pages/docs/index.mdx, website/pages/docs/migrate.mdx, website/pages/docs/pure.mdx, website/pages/docs/sdk/distribute.mdx, website/pages/docs/sdk/e2e.mdx, website/pages/docs/sdk/index.mdx, website/pages/docs/sdk/sdk.mdx, website/pages/docs/sdk/simulate.mdx, website/pages/docs/sdk/simulator.mdx, website/pages/docs/sdk/swagger.mdx, website/pages/docs/setup.mdx, website/pages/docs/swagger/_meta.js, website/pages/docs/swagger/chat.mdx, website/pages/docs/swagger/editor.mdx, website/pages/docs/swagger/index.mdx, website/pages/docs/swagger/strategy.mdx, website/pages/index.mdx, website/theme.config.tsx
This pull request includes updates to the documentation files in the `website/pages/docs` directory. The primary change is the addition of front matter metadata to each file, which includes a title for the documentation page. This change ensures that each documentation page has a consistent and descriptive title.
* Added front matter metadata with titles to core library documentation pages (`TypedBody.mdx`, `TypedException.mdx`, `TypedFormData.mdx`, `TypedHeaders.mdx`, `TypedParam.mdx`, `TypedQuery.mdx`, `TypedRoute.mdx`, `WebSocketRoute.mdx`). [[1]](diffhunk://#diff-7f2e03cbf57f8200cac429539081731bc647a550b27db0bfe2fb5104aa6ae14dR1-R3) [[2]](diffhunk://#diff-29a1bc9dd97106bb4cfea3a17c78b01f0a4aa7cedb7d0fba93cec1ce7d5f4f7eR1-R4) [[3]](diffhunk://#diff-63ab26f5146652342f78f2a9b23fa8f51c350c …
=> Assign titles for each website

packages/agent/package.json, packages/agent/src/module.ts, packages/agent/src/structures/INestiaAgentContext.ts
This pull request includes several updates to the `@nestia/agent` package, focusing on version updates, new exports, and enhancements to the `INestiaAgentContext` interface. Below are the most important changes:
* Updated the `@nestia/agent` package version from `0.3.10` to `0.3.11` in `packages/agent/package.json`.
* Updated dependencies in `packages/agent/package.json`:
- `@samchon/openapi` from `^2.4.1` to `^2.4.2`
- `openai` from `^4.77.0` to `^4.82.0`
- `typia` from `^7.6.0` to `^7.6.3`
* Added new exports in `packages/agent/src/module.ts`:
- `INestiaAgentContext`
- `INestiaAgentOperationCollection`
- `NestiaAgentSource`
* Introduced a detailed JSDoc comment to explain the `INestiaAgentContext` structure and its components.
* Added several new properties and methods to the …
=> Detailed documentation comments on the agent.

packages/agent/src/chatgpt/ChatGptAgent.ts, packages/agent/src/structures/INestiaAgentConfig.ts, packages/agent/src/structures/internal/__IChatSelectFunctionsApplication.ts, packages/chat/package.json
This pull request includes several updates and improvements across multiple files, focusing on bug fixes, configuration adjustments, and dependency updates. The most important changes include fixing a typo in an internal interface, updating the default capacity in the agent configuration, and upgrading dependencies in the `package.json` file.
* Fixed a typo in the `__IChatSelectFunctionsApplication` interface, changing "speciify" to "specify".
* Updated the default value of `capacity` in the `INestiaAgentConfig` interface from 0 to 100.
* Updated the version of `typia` from `^7.6.0` to `^7.6.2` in `packages/chat/package.json`.
* Updated the version of `openai` from `^4.77.3` to `^4.82.0` in `packages/chat/package.json`.
* Incremented the package version from `0.3.10` to `0.3.11` in …
=> Also deploy the chat following the agent update

website/build/typedoc.js
This pull request includes changes to the `packages/openapi` subproject and updates to the `website/build/typedoc.js` file to incorporate the new subproject and ensure it is properly included in the build process.
Updates to subproject and build process:
* [`packages/openapi`](diffhunk://#diff-a9cb1b791d3f26351f7cfe3ee432ddf0aae61b5afa558e9cbbfb09c9b8a0fb02R1): Added a new subproject commit.
* [`website/build/typedoc.js`](diffhunk://#diff-e42f4d8ceb8336889101cafff758774867fa98cc2b66b2f5f5c202171b3b0638L9-R21): Modified the script to pull the latest changes from the `openapi` subproject repository and included `openapi` in the list of packages to install dependencies for.
=> Add `@samchon/openapi` API documents.

packages/e2e/package.json, packages/e2e/src/DynamicExecutor.ts, packages/e2e/test/index.ts
This pull request introduces several enhancements and updates to the `@nestia/e2e` package, particularly focusing on improving the dynamic execution of functions and adding support for simultaneous requests. The most important changes include updating the package version, adding a new configuration option for simultaneous requests, and refactoring the dynamic executor to handle concurrent processing.
Enhancements to dynamic execution:
* [`packages/e2e/src/DynamicExecutor.ts`](diffhunk://#diff-b0df7fe1fe55993907695fe0a83790aebea7ae1505d17ad0397178b133a9fd47R94-R105): Added a new `simultaneous` configuration option to specify the number of simultaneous requests. This allows the dynamic executor to process functions concurrently with the given capacity value.
* …
=> `e2e/DynamicExecutor` to support simultaneous calling.

.github/workflows/website.yml, pnpm-lock.yaml, website/build/chat.js, website/package.json, website/pages/docs/swagger/chat.mdx, website/src/movies/home/HomeStrengthMovie.tsx
This pull request includes updates to the build process and dependency versions, particularly focusing on the transition to TypeScript 5.8.2 and the stabilization of the `@samchon/openapi` and `typia` libraries.
* [`.github/workflows/website.yml`](diffhunk://#diff-c7731b29de71fca225e1dfac88ebe31975a4cd9759ab13e91d86eeadafbddc10L26-R26): Changed the build command from `npm run build` to `pnpm run build` for consistency with the package manager used in the project.
* [`pnpm-lock.yaml`](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL101-R107): Updated TypeScript version from 5.7.3 to 5.8.2 across multiple dependencies and packages. This ensures compatibility and leverages the latest features and fixes provided by TypeScript 5.8.2. …
=> Re-writing chatbot page

packages/benchmark/deploy/publish.js, packages/benchmark/package.json, pnpm-lock.yaml
This pull request includes several changes to the `packages/benchmark` and `pnpm-lock.yaml` files, focusing on updating dependencies and improving the deployment script. The most important changes include adding a new deployment script, updating the package version, and modifying dependency versions in the `pnpm-lock.yaml`.
* [`packages/benchmark/deploy/publish.js`](diffhunk://#diff-9329c85263dc9d7dc857bcb5fe6fcb0e48b3cf03c77298ff2b9f7df20946d99dR1-R46): Added a new deployment script to handle the publishing process, including updating package versions and managing dependencies.
* [`packages/benchmark/package.json`](diffhunk://#diff-03d34ead8faa24fcf5b6d74b52eaf57db4400f375b60698e3f5024e28b29b0e1R2-R4): Updated the package version from `0.4.0` to `0.4.3` and added the `private` field.
* …
=> Publish benchmark v0.4.3

package.json, packages/migrate/src/MigrateApplication.ts, pnpm-lock.yaml
This pull request includes a version bump for the `@nestia/station` package and updates to the `MigrateApplication` class to filter out specific file paths when generating output files. Below are the most important changes:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L4-R4): Updated the package version from `6.0.3` to `6.0.4`.
* [`packages/migrate/src/MigrateApplication.ts`](diffhunk://#diff-8a36886ef2b2c18013382d39cbc6d752bb4416b87c21179220a9de855aad5f43L47-R53): Modified the `NEST_TEMPLATE` files to exclude files located in `src/api/structures`, `src/api/functional`, `src/api/controllers`, and `test/features`.
* [`packages/migrate/src/MigrateApplication.ts`](diffhunk://#diff-8a36886ef2b2c18013382d39cbc6d752bb4416b87c21179220a9de855a …
=> feat(migrate): filter out generated files

packages/core/package.json, packages/editor/eslint.config.js, packages/editor/package.json, packages/editor/src/NestiaEditorApplication.tsx, packages/editor/src/NestiaEditorIframe.tsx, packages/editor/src/NestiaEditorUploader.tsx, packages/editor/src/internal/NestiaEditorComposer.ts, packages/fetcher/package.json, packages/migrate/package.json, packages/migrate/src/executable/NestiaMigrateInquirer.ts, packages/sdk/package.json, pnpm-lock.yaml
This pull request introduces several changes across multiple packages, focusing on dependency updates, added functionality for handling a `keyword` parameter, and improvements to code formatting and configuration. The most significant changes involve updating the `@samchon/openapi` dependency, integrating new Prettier plugins, and extending functionality related to the `keyword` parameter.
* Updated `@samchon/openapi` dependency from version `^4.3.2` to `^4.3.3` across multiple packages (`packages/core/package.json`, `packages/editor/package.json`, `packages/fetcher/package.json`, `packages/migrate/package.json`, `packages/sdk/package.json`, `pnpm-lock.yaml`). [[1]](diffhunk://#diff-0b810c38f3c138a3d5e44854edefd5eb966617ca84e62f06511f60acc40546c7L42-R42) …
=> feat(editor): support keyword parameter

packages/migrate/src/programmers/NestiaMigrateApiNamespaceProgrammer.ts
This pull request refactors the `NestiaMigrateApiNamespaceProgrammer` in `packages/migrate/src/programmers/NestiaMigrateApiNamespaceProgrammer.ts` to improve code readability and simplify parameter handling. The changes primarily involve replacing the identifier `p` with `props` and modifying the way schema-related parameters are handled.
* Replaced the identifier `p` with `props` for better clarity in accessing properties. (`[packages/migrate/src/programmers/NestiaMigrateApiNamespaceProgrammer.tsL232-R232](diffhunk://#diff-74287fee092d719353a974c05dcca856d9fdaf8684a6c7c0661b8624a2fd587fL232-R232)`)
* Simplified schema-related parameter handling by replacing the detailed schema generation logic with a type reference to `Props`. Additionally, introduced conditional logic to handle cases …
=> feat(migrate): path function also use 'Props' type.

package.json, packages/migrate/src/programmers/NestiaMigrateNestMethodProgrammer.ts, packages/migrate/src/structures/INestiaMigrateConfig.ts
This pull request refines the migration logic in the `NestiaMigrate` package by improving type definitions and enhancing the flexibility of the `controllerMethod` configuration. The most important changes include updating the `controllerMethod` signature to accept a broader context and removing an unused import.
* [`packages/migrate/src/programmers/NestiaMigrateNestMethodProgrammer.ts`](diffhunk://#diff-f1e99926dfd3ccda6c85d3229ccbbdfe3fa70438546002a48aa56ff1eb58e2d0L45-R45): Updated the `controllerMethod` invocation to pass the full `ctx` object instead of just `ctx.route`, enabling more comprehensive access to context data.
* [`packages/migrate/src/structures/INestiaMigrateConfig.ts`](diffhunk://#diff-68fb008bf245a8926aab6a9f81f1998f973ebe8adf68f5581971c360a1aa3a40L14-R17): Modified the …
=> Change `INestiaMigrateConfig`'s programmer type

package.json, packages/migrate/src/programmers/NestiaMigrateNestControllerProgrammer.ts, packages/migrate/src/programmers/NestiaMigrateNestMethodProgrammer.ts, packages/migrate/src/structures/INestiaMigrateConfig.ts
This pull request introduces updates to versioning, enhances configurability in the migration programmer, and refines type definitions for improved flexibility. The most significant changes include updating the package version, adding support for custom controller method programmers, and modifying type definitions for programmer configuration.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L4-R4): Updated the version from `7.2.4` to `7.2.5`.
* [`packages/migrate/src/programmers/NestiaMigrateNestControllerProgrammer.ts`](diffhunk://#diff-942e7c6253aa3a0ff15f10b58d3b4f12fc7207ab8312fe517d91e87c3536193eL44-R47): Added support for custom controller method programmers by invoking `props.config.programmer?.controllerMethod` if defined, …
=> Change programmer method once more

benchmark/package.json, package.json, packages/benchmark/package.json, packages/cli/package.json, packages/core/package.json, packages/core/src/decorators/TypedFormData.ts, packages/e2e/package.json, packages/editor/package.json, packages/fetcher/package.json, packages/migrate/package.json, packages/sdk/package.json, pnpm-lock.yaml, test/features/distribute-assert-json/packages/api/package.json, test/features/distribute-assert/packages/api/package.json, test/features/distribute-json/packages/api/package.json, test/features/distribute/packages/api/package.json, test/package.json, website/package.json
This pull request updates dependencies across multiple packages to ensure compatibility and leverage the latest features and fixes. The key changes include upgrading `typescript` and `typia` versions in various `package.json` files.
* Upgraded `typescript` from `~5.8.3` to `~5.9.2` across multiple packages, including `benchmark`, `cli`, `core`, `e2e`, `editor`, `fetcher`, `migrate`, `sdk`, `test`, and `website` (`benchmark/package.json` [[1]](diffhunk://#diff-ebd18337ce8dc8b96a8403d2731d05bbb7502293037672a62faa622e36d2821aL56-R56) `packages/cli/package.json` [[2]](diffhunk://#diff-6e2e2a1851648938b325ba84de634407a4e69a644ea61102df15ca4a8a7a9758L45-R45) `packages/core/package.json` [[3]](diffhunk://#diff-0b810c38f3c138a3d5e44854edefd5eb966617ca84e62f06511f60acc40546c7L83-R83) …
=> Bump up TypeScript to v5.9.2

package.json, packages/migrate/assets/input/v3.1/setHeaders.json, packages/migrate/src/programmers/NestiaMigrateApiFunctionProgrammer.ts
This pull request introduces support for parsing and handling custom header assignment directives (`@setHeader` and `@assignHeaders`) in API endpoint descriptions, and updates the OpenAPI input and package version accordingly. The changes enhance how headers are set or assigned in generated API functions based on OpenAPI comments.
Key changes include:
**Header Assignment and Parsing Enhancements:**
* Added logic in `NestiaMigrateApiFunctionProgrammer.ts` to parse `@setHeader` and `@assignHeaders` directives from route descriptions, generating corresponding TypeScript code to set or assign headers in the API response. [[1]](diffhunk://#diff-d248141e49ffcafb2ad3e2ad3cb8d99f04cacf101dee90127914c7ae6adb72e9R240-R280) [[2]](diffhunk://#diff-d248141e49ffcafb2ad3e2ad3cb8d99f04cacf101dee90127914c7 …
=> Complete #1364: `@setHeader` and `@assignHeaders` in `@nestia/migrate`.

package.json, packages/migrate/src/programmers/NestiaMigrateSchemaProgrammer.ts
This pull request includes a minor version bump and a small logic improvement for handling schema extensions. The most important changes are:
Version update:
* Bumped the package version from `8.0.1` to `8.0.2` in `package.json` to reflect the latest changes.
Schema extension handling:
* Updated the logic in `NestiaMigrateSchemaProgrammer.ts` so that only schema keys starting with `"x-"` (custom extensions) are included in the `extra` object, ensuring that only valid extension properties are processed.
=> Let `@nestia/migrate` to use JsonSchemaPlugin for only `x-` starting properties.
