samchon/nestia

demo/encrypt/swagger.json, package.json, src/executable/internal/CompilerOptions.ts, src/generates/SwaggerGenerator.ts, src/structures/ISwagger.ts
=> Close #96 and Close #97

demo/array/src/api/structures/ISaleArticleComment.ts, demo/array/swagger.json, demo/generic/src/api/structures/ISaleArticle.ts, demo/generic/swagger.json, demo/simple/src/api/structures/ISaleArticleComment.ts, demo/simple/swagger.json, demo/union/swagger.json, package.json
Enhance swagger generator through new version of `typescript-json`
=> Close #110

demo/array/swagger.json, demo/encrypt/swagger.json, demo/generic/swagger.json, demo/recursive/swagger.json, demo/simple/swagger.json, demo/union/swagger.json, package.json, src/generates/SwaggerGenerator.ts
=> Rollback TypeScript version from 4.7 to 4.6

demo/array/swagger.json, demo/simple/swagger.json, demo/union/swagger.json, package.json, src/analyses/ReflectAnalyzer.ts
Support https://github.com/samchon/nestia-helper/issues/25
=> Close #121

package.json, src/executable/internal/NestiaCommand.ts
=> Fix #126 - Support extended tsconfig.json

src/executable/internal/NestiaConfig.ts
=> Fix #127 - Error loading nestia.config.ts if compilerOptions.module is changed

src/IConfiguration.ts, src/utils/StripEnums.ts
=> Fix #129 - Correct typing for compilerOptions

package.json, preliminaries/nestia.config.ts, src/executable/nestia.ts
Start supporting `npx nestia init` command.
=> Close #148, new command `npx nestia init`

demo/union/src/api/functional/consumers/sales/entire_articles/index.ts, demo/union/src/api/functional/consumers/sales/questions/index.ts, demo/union/src/controllers/ConsumerSaleEntireArticlesController.ts, demo/union/src/controllers/ConsumerSaleQuestionsController.ts, demo/union/swagger.json, package.json, src/generates/FunctionGenerator.ts
=> Fix #152, when `@Query(field)` and its parameter name are different

demo/encrypted/swagger.json, demo/generic/swagger.json, demo/multiple-paths/swagger.json, demo/recursive/swagger.json, demo/safe/swagger.json, demo/union/swagger.json, package.json
```bash
npm run build
npm run test
```
=> Fix #155, cannot find module bug

.npmignore, README.md, demo/encrypted/src/controllers/SellerAuthenticateController.ts, demo/union/swagger.json, package.json, src/executable/internal/NestiaStarter.ts, src/executable/nestia.ts
From now on, coyping boilerplate project command has been supported:
```bash
npx nestia start <directory>
```
=> Close #163 - `npx nestia start`

README.md, package.json, src/executable/internal/NestiaStarter.ts
```bash
npm run build
npm run test
```
=> Close #165 - let `npx nestia start` to clone repo

demo/encrypted/swagger.json, demo/generic/src/api/functional/consumers/sales/questions/index.ts, demo/generic/src/api/functional/consumers/sales/reviews/index.ts, demo/generic/swagger.json, demo/multiple-paths/swagger.json, demo/recursive/swagger.json, demo/safe/swagger.json, demo/union/swagger.json, package.json, src/analyses/ImportAnalyzer.ts
```bash
npm run build
npm run test
```
=> Close #176 - support alias type

packages/core/README.md, packages/core/package.json
```bash
npm run build
npm run test
```
=> Writing #188 - README of `@nestia/core`

README.md, package.json, packages/core/README.md, packages/core/package.json, packages/fetcher/package.json, packages/sdk/package.json, src/index.ts
```bash
npm run build
npm run test
```
=> Make README concise

package.json, packages/core/package.json, packages/fetcher/package.json, packages/sdk/package.json
```bash
npm run build
npm run test
```
=> Publish namespaced modules

packages/core/package.json, packages/core/src/decorators/EncryptedRoute.ts, packages/core/src/decorators/internal/get_path_and_stringify.ts, packages/core/src/options/INestiaTransformOptions.ts, packages/core/src/transformers/RouteTransformer.ts
```bash
npm run build
npm run test
```
=> Close #196 - allow `TypedRoute` to use native `JSON.stringify()`

packages/core/package.json, packages/core/src/decorators/EncryptedRoute.ts, packages/core/src/decorators/TypedRoute.ts, packages/core/src/executable/internal/CoreSetupWizard.ts
```bash
npm run build
npm run test
```
=> Close #197 - `npx nestia setup` configures detailed options

README.md, packages/core/README.md
```bash
npm run build
npm run test
```
=> Change README content a little bit

package.json, packages/core/package.json, packages/core/src/decorators/DynamicModule.ts, packages/core/src/decorators/EncryptedModule.ts, packages/core/src/executable/internal/CoreSetupWizard.ts, src/NestiaSetupWizard.ts
```bash
npm run build
npm run test
```
=> Close #201 - `DynamicModule` supports detailed options

packages/core/package.json, packages/core/src/options/INestiaTransformOptions.ts, packages/core/src/transform.ts, packages/core/src/transformers/BodyTransformer.ts, packages/core/src/transformers/RouteTransformer.ts
```bash
npm run build
npm run test
```
=> Close #204 - turn off `numeric` options in request body

README.md, package.json, packages/core/README.md, packages/core/package.json, packages/core/src/executable/core.ts, packages/core/src/executable/internal/CoreSetupWizard.ts, src/NestiaSetupWizard.ts, src/index.ts
```bash
npm run build
npm run test
```
=> Close #206 - `npx nestia setup --project` command

packages/core/package.json, packages/core/src/decorators/TypedBody.ts, packages/sdk/src/structures/ISwagger.ts
```bash
npm run build
npm run test
```
=> Fix #218 - bug from content-type parsing

packages/sdk/demo/176/src/api/functional/userspace/index.ts, packages/sdk/demo/encrypted/src/api/functional/sellers/authenticate/index.ts, packages/sdk/demo/encrypted/src/api/functional/sellers/authenticate/password/index.ts, packages/sdk/demo/generic/src/api/functional/consumers/sales/questions/index.ts, packages/sdk/demo/generic/src/api/functional/consumers/sales/reviews/index.ts, packages/sdk/demo/multiple-paths/src/api/functional/consumers/sales/articles/comments/index.ts, packages/sdk/demo/multiple-paths/src/api/functional/health/alive/index.ts, packages/sdk/demo/multiple-paths/src/api/functional/health/index.ts, packages/sdk/demo/multiple-paths/src/api/functional/healthy/alive/index.ts, packages/sdk/demo/multiple-paths/src/api/functional/healthy/index.ts, packages/sdk/demo/multiple-paths/src/api/functional/sellers/sales/articles/comments/index.ts, packages/sdk/demo/recursive/src/api/functional/consumers/systematic/categories/index.ts, packages/sdk/demo/safe/src/api/functional/consumers/sales/articles/comments/index.ts, packages/sdk/demo/union/src/api/functional/consumers/sales/entire_articles/index.ts, packages/sdk/demo/union/src/api/functional/consumers/sales/questions/index.ts, packages/sdk/demo/union/src/api/functional/consumers/sales/reviews/index.ts, packages/sdk/src/generates/FunctionGenerator.ts
```bash
npm run build
npm run test
```
=> Complement #222 - generated code styling

packages/core/README.md, packages/sdk/README.md
```bash
npm run build
npm run test
```
=> Complement#233 - edit README of sub-modules

packages/sdk/demo/generic/src/controllers/ConsumerSaleQuestionsController.ts, packages/sdk/demo/generic/src/controllers/ConsumerSaleReviewsController.ts, packages/sdk/demo/generic/src/test/features/test_question_store.ts, packages/sdk/demo/generic/src/test/features/test_question_update.ts, packages/sdk/demo/generic/src/test/features/test_review_store.ts, packages/sdk/demo/generic/src/test/features/test_review_update.ts, packages/sdk/demo/safe/src/test/features/test_comment_store.ts, packages/sdk/package.json, packages/sdk/prettier.config.js, packages/sdk/src/executable/internal/NestiaSdkConfig.ts, packages/sdk/src/generates/FunctionGenerator.ts, packages/sdk/src/generates/SwaggerGenerator.ts, packages/sdk/src/index.ts
```bash
npm run build
npm run test
```
=> Close #236 - swagger generator ignores `@internal` tagged API

README.md, package.json, packages/core/package.json, packages/core/src/decorators/DynamicModule.ts, packages/core/src/decorators/EncryptedBody.ts, packages/core/src/decorators/EncryptedRoute.ts, packages/core/src/decorators/TypedBody.ts, packages/core/src/decorators/TypedParam.ts, packages/core/src/decorators/TypedQuery.ts, packages/core/src/decorators/TypedRoute.ts, packages/core/src/decorators/internal/TransformError.ts, packages/core/src/decorators/internal/get_path_and_stringify.ts, packages/core/src/decorators/internal/validate_request_body.ts, src/NestiaSetupWizard.ts
```bash
npm run build
npm run test
```
=> Complement #209 - documentation by comments

packages/sdk/package.json, packages/sdk/src/generates/SwaggerGenerator.ts
```bash
npm run build
npm run test
```
=> Fix SwaggerGenerator bug, writing duplicated security values

packages/sdk/demo/safe/swagger.json, packages/sdk/package.json, packages/sdk/src/generates/SwaggerGenerator.ts, packages/sdk/src/structures/ISwaggerDocument.ts
```bash
npm run build
npm run test
```
=> Fix #240 - `ISwaggerDocuments.security`

package.json, packages/core/package.json, packages/core/src/executable/internal/ArgumentParser.ts, packages/core/src/executable/internal/FileRetriever.ts, packages/core/src/executable/internal/PackageManager.ts, packages/core/src/executable/internal/PluginConfigurator.ts, packages/sdk/package.json, src/index.ts, src/internal/ArgumentParser.ts, src/internal/FileRetriever.ts, src/internal/PackageManager.ts, src/internal/PluginConfigurator.ts
```bash
npm run build
npm run test
```
=> Fix #251 - support yarn monorepo in setup wizard

packages/fetcher/src/Fetcher.ts
=> fix(@nestia/fetcher): incorrect overloading of fetcher functions

packages/sdk/demo/union/src/api/functional/consumers/sales/entire_articles/index.ts, packages/sdk/demo/union/src/api/functional/consumers/sales/questions/index.ts, packages/sdk/demo/union/src/api/functional/consumers/sales/reviews/index.ts, packages/sdk/demo/union/src/controllers/ConsumerSaleQuestionsController.ts, packages/sdk/demo/union/swagger.json, packages/sdk/package.json, packages/sdk/src/generates/FunctionGenerator.ts
```bash
npm run build
npm run test
```
=> Fix #268 - when optional query param comes

packages/sdk/package.json
```bash
npm run build
npm run test
```
=> Close #277 - `IJsonSchema.INumeric.exclusiveMinimum`

packages/e2e/package.json, packages/e2e/src/TestValidator.ts, packages/e2e/src/test/features/internal/generate_random_articles.ts, packages/e2e/src/test/features/structures/IBbsArticle.ts, packages/e2e/src/test/features/test_validate_search.ts
```bash
npm run build
npm run test
```
=> Close #280 - `TestValidator.search()`

package.json, packages/core/package.json, packages/core/src/executable/core.ts, packages/core/src/executable/internal/ArgumentParser.ts, packages/core/src/transformers/MethodTransformer.ts, packages/sdk/package.json, packages/sdk/src/analyses/ImportAnalyzer.ts, src/NestiaSetupWizard.ts, src/internal/ArgumentParser.ts
From now on, no problem when too long type name comes.
=> Fix #282 - too long type name

packages/core/package.json, packages/core/src/decorators/EncryptedBody.ts, packages/core/src/decorators/EncryptedRoute.ts, packages/core/src/decorators/TypedBody.ts, packages/core/src/decorators/TypedRoute.ts, packages/core/test/features/test_comments.ts, packages/core/test/features/test_filesystem.ts, packages/core/test/features/test_questions.ts, packages/core/test/features/test_reviews.ts, packages/core/test/features/test_system.ts
Shuffled sequence of function composition for exact type error message construction.
=> Fix #288 - exact type error message

packages/e2e/package.json, packages/e2e/src/TestValidator.ts, packages/e2e/src/internal/json_equal_to.ts, packages/e2e/src/test/features/test_validate_equals.ts, packages/e2e/src/test/features/test_validate_predicate.ts, packages/e2e/tsconfig.json
```bash
npm run build
npm run test
```
=> Add `predicate()` and `equals()` functions in `e2e.TestValidator`

packages/e2e/.eslintrc.cjs, packages/e2e/package.json, packages/e2e/src/TestValidator.ts, packages/e2e/src/test/features/test_validate_error.ts, packages/e2e/src/test/features/test_validate_index.ts, packages/e2e/src/test/features/test_validate_predicate.ts, packages/e2e/src/test/features/test_validate_search.ts
```bash
npm run build
npm run test
```
=> Enhance `TestValidator` to support both sync/async

.eslintrc.cjs, .prettierignore, README.md, package.json, packages/core/README.md, packages/core/package.json, packages/core/src/transformers/MethodTransformer.ts, packages/core/src/transformers/ParameterTransformer.ts, prettier.config.js, src/NestiaSetupWizard.ts, src/index.ts, src/internal/ArgumentParser.ts
From now on, `nestia` starts supporting TS5 through `ts-patch`
=> Support TS5

packages/fetcher/package.json, packages/fetcher/src/Primitive.ts
@kakasoo has advanced `Primitive` type in `typia`, and `nestia` also accepts it.
https://github.com/samchon/typia/pull/601
=> Change `Primitive` type to support tuple types

packages/core/package.json, packages/core/src/decorators/TypedQuery.ts, packages/core/src/programmers/TypedQueryProgrammer.ts, packages/core/test/api/structures/IFilesystemBucket.ts, website/pages/docs/core/TypedQuery.mdx
```bash
npm run build
npm run test
```
=> Complement #301 - `TypedQuery()` allow nullable types

packages/core/package.json, packages/core/src/decorators/TypedQuery.ts, packages/core/src/programmers/TypedBodyProgrammer.ts, packages/core/src/programmers/TypedQueryProgrammer.ts, packages/core/src/programmers/TypedRouteProgrammer.ts, packages/core/src/transformers/MethodDecoratorTransformer.ts, packages/core/src/transformers/ParameterDecoratorTransformer.ts, packages/core/test/features/test_filesystem.ts
```bash
npm run build
npm run test
```
=> Close #320: `TypedQuery` also throws 400 status error

packages/core/src/decorators/internal/TransformError.ts, packages/e2e/README.md, packages/e2e/package.json, packages/e2e/src/ArrayUtil.ts, packages/e2e/src/RandomGenerator.ts, packages/e2e/src/StopWatch.ts, packages/e2e/src/TestValidator.ts, packages/e2e/src/test/features/internal/generate_random_articles.ts
```bash
npm run build
npm run test
```
=> Make `@nestia/e2e` to be much functional

packages/sdk/package.json, packages/sdk/src/NestiaSdkApplication.ts, packages/sdk/src/generates/E2eGenerator.ts, packages/sdk/src/generates/SdkGenerator.ts, packages/sdk/src/generates/SwaggerGenerator.ts, test/features/distribute-assert/packages/api/package.json, test/features/distribute-json/packages/api/package.json, test/features/distribute/packages/api/package.json
When running `@nestia/sdk` from CLI, such texts would be printed in console.
```bash
-----------------------------------------------------------
Nestia SDK Generator
-----------------------------------------------------------
Analyzing reflections
- controllers: #6
- paths: #15
- routes: #15
Analyzing source codes
Generating SDK Library
```
=> Print some descriptions when running `@nestia/sdk`

website/pages/docs/core/TypedBody.mdx, website/pages/docs/core/TypedQuery.mdx, website/pages/docs/core/TypedRoute.mdx, website/public/sitemap-0.xml
```bash
npm run build
npm run test
```
=> Fix #343 - broken links in website

website/pages/docs/core/TypedRoute.mdx
Fix typing mistake in website's TypeRoute.
compliation to compilation.
https://nestia.io/docs/core/TypedRoute/
2nd paragraph's 1st sentence in TypeRoute - How to Use.
=> Fix typo in website's TypeRoute

packages/sdk/assets/bundle/e2e/index.ts, packages/sdk/package.json, test/features/body-manual-assert/src/test/index.ts, test/features/body-manual-is/src/test/index.ts, test/features/body-manual-validate/src/test/index.ts, test/features/body/src/test/index.ts, test/features/cli-directory/src/test/index.ts, test/features/cli-pattern/src/test/index.ts, test/features/config-pattern/src/test/index.ts, test/features/duplicated/src/test/index.ts, test/features/e2e/src/test/index.ts, test/features/encrypted/src/test/index.ts, test/features/exception-filter/src/test/index.ts, test/features/fastify/src/test/index.ts, test/features/param/src/test/index.ts, test/features/plain/src/test/index.ts, test/features/query/src/test/index.ts, test/features/route-manual-assert/src/test/index.ts, test/features/route-manual-is/src/test/index.ts, test/features/route-manual-stringify/src/test/index.ts, test/features/route-manual-validate/src/test/index.ts, test/features/route/src/test/index.ts, test/features/status/src/test/index.ts, test/features/swagger/src/test/index.ts, test/package.json, test/template/success/src/test/index.ts
```bash
npm run build
npm run test
```
=> Complement #353 - restore test automation programs

packages/fetcher/package.json, packages/fetcher/src/Primitive.ts, test/package.json
Same update with `typia` contributed by @8471919
- https://github.com/samchon/typia/pull/656
=> Evolve `Primitive` type

benchmark/package.json, packages/core/package.json, packages/sdk/package.json, test/features/distribute-assert/packages/api/package.json, test/features/distribute-json/packages/api/package.json
Upgrade by https://github.com/samchon/typia/pull/659
That issue can affects on simulation mode, therefore updated to new patch version.
=> Upgrade dependencies

.github/ISSUE_TEMPLATE/QUESTION.md
=> Fix typo in QUESTION.md

packages/sdk/package.json, test/features/distribute-assert/packages/api/package.json, test/features/distribute-json/packages/api/package.json, test/package.json
Typia has changed `IJsonSchema.ITuple` type.
- https://github.com/samchon/typia/pull/668
=> Update typia version in SDK

packages/fetcher/src/Fetcher.ts, packages/fetcher/src/IConnection.ts
- Edit a suggestion #412
```bash
npm run build
npm run test
```
=> Add credentials to fetcher IConnection #411

packages/fetcher/package.json, packages/fetcher/src/Fetcher.ts, packages/fetcher/src/IConnection.ts
Added option properties of `fetch()` function into `IConnection.options`. 
The `credentials` property suggested by @SeungjunWe also in there.
=> Complement #411 - `IConnection.options`

benchmark/package.json, packages/core/package.json, packages/e2e/package.json, packages/sdk/package.json, test/features/distribute-assert/packages/api/package.json, test/features/distribute-json/packages/api/package.json, test/features/distribute/packages/api/package.json, test/package.json
Typia enhanced JSON schema generator, and Nestia accepts it.
=> Upgrade typia version

website/pages/docs/sdk/swagger.mdx
Add "@summary" descriptions to controller methods
=> Add "@summary" descriptions

packages/sdk/package.json, packages/sdk/src/generates/SwaggerGenerator.ts, packages/sdk/src/structures/ISwaggerDocument.ts, website/pages/docs/_meta.json
=> Support `@deprecated` tag of swagger in controller

website/pages/docs/sdk/swagger.mdx
=> controller methods - "@summery" -> "@summary"

packages/sdk/package.json, packages/sdk/src/generates/E2eGenerator.ts, packages/sdk/src/generates/internal/E2eFileProgrammer.ts, packages/sdk/src/utils/PathUtil.ts, test/features/body/src/controllers/TypedBodyController.ts
When last part of path and controller method name is equal, e2e test function generator had a problem.
Fix that bug.
=> Exact SDK accessor in E2E generator

packages/sdk/package.json, packages/sdk/src/analyses/ControllerAnalyzer.ts, packages/sdk/src/analyses/ReflectAnalyzer.ts, packages/sdk/src/generates/SwaggerGenerator.ts, packages/sdk/src/generates/internal/E2eFileProgrammer.ts, packages/sdk/src/generates/internal/SdkFunctionProgrammer.ts, packages/sdk/src/generates/internal/SdkSimulationProgrammer.ts, packages/sdk/src/structures/IController.ts, packages/sdk/src/structures/IRoute.ts, packages/sdk/src/structures/ISwaggerDocument.ts
`@nestia/sdk` starts supporting `text/plain` typed body.
=> Support text/plain body on SDK

benchmark/package.json, benchmark/src/internal/BenchmarkServer.ts, benchmark/src/programs/assert/createAssertBenchmarkProgram.ts, benchmark/src/programs/assert/servers/createNestExpressAssertProgram.ts, benchmark/src/programs/assert/servers/createNestFastifyAssertProgram.ts, benchmark/src/programs/performance/createPerformanceBenchmarkProgram.ts, benchmark/src/programs/performance/servers/createNestExpressPerformanceProgram.ts, benchmark/src/programs/performance/servers/createNestFastifyPerformanceProgram.ts, benchmark/src/programs/stringify/servers/createNestExpressStringifyProgram.ts, benchmark/src/programs/stringify/servers/createNestFastifyStringifyProgram.ts
Configure `stopAtFirstError` option to be `true`.
=> Let `class-validator` to find only the first error in benchmark program

website/pages/docs/setup.mdx
This is a tiny fix of a typo on the website.
=> Fix website typo

packages/migrate/package.json, packages/migrate/src/NestiaMigrateApplication.ts, packages/migrate/src/archivers/FileArchiver.ts, packages/migrate/src/programmers/RouteProgrammer.ts, packages/migrate/src/structures/IMigrateRoute.ts, packages/migrate/src/structures/ISwaggerRoute.ts
Nestia has been evolved during 1.5 updates. Made `@nestia/migrate` to follow that evolution, too.
=> Upgrade `@nestia/migrate` following 1.5 spec

website/pages/docs/setup.mdx, website/public/sitemap-0.xml
Changed setup contents of website.
=> Complement samchon/typia#744 - change setup document contents

benchmark/package.json, packages/cli/package.json, packages/core/package.json, packages/e2e/package.json, packages/fetcher/package.json, packages/migrate/package.json, packages/sdk/package.json, test/features/distribute-assert/packages/api/package.json, test/features/distribute-json/packages/api/package.json, test/package.json
Related with samchon/typia#749
=> Update `typia` dependency version

website/pages/docs/setup.mdx
```bash
npm run build
npm run test
```
=> update: docs setup for nx project

packages/sdk/src/analyses/ControllerAnalyzer.ts, packages/sdk/src/generates/SwaggerGenerator.ts, packages/sdk/src/structures/IRoute.ts, packages/sdk/src/structures/ISwaggerRoute.ts
Here is my atempt at adding the operationid based on https://github.com/samchon/nestia/issues/551
Schema is generating fine. i just have no clue on how to implement a test for it
=> Adding the operation id

packages/sdk/src/INestiaConfig.ts, packages/sdk/src/executable/internal/NestiaSdkCommand.ts
I tested on my own project, but I cannot find any existing unit test in sdk package to lookup. Any guide for me to follow?
=> feat: ability to customize tsconfig path

packages/core/package.json, packages/fetcher/package.json, packages/fetcher/src/internal/IFetchRoute.ts, packages/migrate/package.json, packages/migrate/src/programmers/RouteProgrammer.ts, packages/migrate/src/structures/IMigrateRoute.ts, packages/migrate/src/structures/ISwaggerRoute.ts, packages/sdk/package.json, test/package.json
Have published the v2.2 update.
=> Publish v2.2 with `@nestia/migrate`

website/pages/docs/core/TypedBody.mdx, website/pages/docs/core/TypedQuery.mdx, website/pages/docs/core/TypedRoute.mdx, website/public/sitemap-0.xml
Updates of https://nestia.io/docs
=> Documentations

packages/core/package.json, packages/fetcher/package.json, packages/fetcher/src/IConnection.ts, packages/fetcher/src/internal/FetcherBase.ts, packages/migrate/package.json, packages/migrate/src/programmers/ControllerProgrammer.ts, packages/migrate/src/programmers/MigrateProgrammer.ts, packages/sdk/package.json, packages/sdk/src/NestiaSdkApplication.ts, packages/sdk/src/executable/sdk.ts, test/package.json
For someone who needs custom fetch function instead of the built-in, I've added a new property `IConnection.fetch` which has the same function type with the built-in following the suggestion of @thenbe.
=> Close #689: custom fetch

website/pages/docs/sdk/swagger.mdx
Fix Typo in swagger.mdx
```bash
npm run build
npm run test
```
=> Fix(typo): update swagger.mdx

packages/e2e/package.json, packages/e2e/src/TestValidator.ts, packages/e2e/src/test/features/test_validate_sort.ts
Just made the 3rd generic parameter to be optional.
=> Enhance `TestValidator.sort()` function.

packages/migrate/package.json, packages/migrate/src/MigrateApplication.ts, packages/migrate/src/analyzers/MigrateAnalyzer.ts, packages/migrate/src/analyzers/MigrateControllerAnalyzer.ts, packages/migrate/src/analyzers/MigrateMethodAnalyzer.ts, packages/migrate/src/archivers/MigrateFileArchiver.ts, packages/migrate/src/executable/bundle.ts, packages/migrate/src/internal/MigrateCommander.ts, packages/migrate/src/programmers/MigrateApiFileProgrammer.ts, packages/migrate/src/programmers/MigrateApiFunctionProgrammer.ts, packages/migrate/src/programmers/MigrateApiNamespaceProgrammer.ts, packages/migrate/src/programmers/MigrateApiProgrammer.ts, packages/migrate/src/programmers/MigrateApiSimulatationProgrammer.ts, packages/migrate/src/programmers/MigrateDtoProgrammer.ts, packages/migrate/src/programmers/MigrateImportProgrammer.ts, packages/migrate/src/programmers/MigrateNestControllerProgrammer.ts, packages/migrate/src/programmers/MigrateNestMethodProgrammer.ts, packages/migrate/src/programmers/MigrateNestModuleProgrammer.ts, packages/migrate/src/programmers/MigrateNestProgrammer.ts, packages/migrate/src/programmers/MigrateSchemaProgrammer.ts, packages/migrate/src/structures/IMigrateRoute.ts, packages/migrate/src/test/index.ts, packages/migrate/src/utils/FilePrinter.ts, packages/migrate/src/utils/SwaggerTypeChecker.ts
To utilize `@nestia/migrate` components in other programs.
=> Refactoring of `@nestia/migrate`.

package.json, packages/migrate/package.json, packages/migrate/src/internal/MigrateCommander.ts, packages/migrate/src/programmers/MigrateNestModuleProgrammer.ts, packages/migrate/src/test/index.ts, packages/sdk/src/generates/SwaggerGenerator.ts
Adjusted prettier to every generated files by `@nestia/migrate`
=> Beautify `@nestia/migrate` generated files.

packages/migrate/assets/input/bbs.json, packages/migrate/assets/input/shopping.json, packages/migrate/package.json, packages/migrate/src/programmers/MigrateApiNamespaceProgrammer.ts, packages/migrate/src/programmers/MigrateNestMethodProgrammer.ts
When there's an endpoint that doing not response anything, `@nestia/migrate` had omitted to writing the `@TypedRoute()` decorator.
This PR fixes the bug
=> Fix `@nestia/migrate` bug of omitting `@TypedRoute()`.

website/pages/docs/core/TypedFormData.mdx
fix typo Complied -> Compiled
```bash
npm run build
npm run test
```
=> fix: fix typo, Complied -> Compiled

website/pages/docs/core/TypedFormData.mdx
```bash
npm run build
npm run test
```
=> Fix typo in TypedFormData.mdx

package.json, packages/core/package.json, packages/fetcher/package.json, packages/sdk/package.json, packages/sdk/src/INestiaConfig.ts, packages/sdk/src/generates/SwaggerGenerator.ts, packages/sdk/src/structures/ISwagger.ts, packages/sdk/src/structures/ISwaggerServer.ts, packages/sdk/src/structures/ISwaggerTag.ts, test/features/tags/nestia.config.ts, test/features/tags/src/api/functional/bbs/articles/index.ts, test/features/tags/src/controllers/BbsArticlesController.ts, test/features/tags/swagger.json, test/package.json, website/pages/docs/sdk/swagger.mdx
```typescript
@ApiTags("common")
@Controller("bbs/articles/:section")
export class BbsArticlesController {
/**
* Would be shown without any mark.
*
* @tag public Some description describing public group...
* @summary Public API
* @param section Section code
* @param input Content to store
* @returns Newly archived article
*/
@ApiTags("protected")
@TypedRoute.Post()
public async store(
@TypedParam("section") section: string,
@TypedBody() input: IBbsArticle.IStore,
): Promise<IBbsArticle> {
return {
...typia.random<IBbsArticle>(),
...input,
section,
};
}
```
=> Support swagger tag description

packages/core/package.json, packages/core/src/adaptors/WebSocketAdaptor.ts, packages/core/src/decorators/TypedQuery.ts, packages/core/src/decorators/WebSocketRoute.ts, packages/core/src/decorators/internal/IWebSocketRouteReflect.ts, packages/core/src/decorators/internal/validate_request_body.ts, packages/core/src/decorators/internal/validate_request_form_data.ts, packages/core/src/decorators/internal/validate_request_headers.ts, packages/core/src/decorators/internal/validate_request_query.ts, packages/core/src/module.ts, packages/core/src/transformers/ParameterDecoratorTransformer.ts, packages/core/src/typings/get-function-location.d.ts, packages/core/src/utils/ArrayUtil.ts
Tested through https://github.com/samchon/nestjs-websocket-study
Everything works fine.
=> Close #715: `@WebSocketRoute()` decorators.

package.json, packages/core/package.json, packages/fetcher/package.json, packages/sdk/package.json, packages/sdk/src/generates/SwaggerGenerator.ts, test/package.json, website/deploy.js
When `@SwaggeCutomizer()`'s `props.at()` function accessed with `@internal` tagged, it becomes error.
This PR fixes the bug by filtering out the `@internal` tagged operations.
> cc: @seunghwako @kakasoo
=> Fix `@SwaggerCuztomizer()` bug of `@internal` tagged.

packages/cli/package.json, packages/cli/src/NestiaSetupWizard.ts
From now on, `npx nestia setup` command installs `@nestia/benchmark`, too.
=> Let CLI to setup `@nestia/benchmark` too.

website/package-lock.json, website/pages/docs/index.mdx, website/pages/docs/sdk/_meta.json, website/pages/docs/sdk/openai.mdx, website/pages/docs/sdk/sdk.mdx, website/pages/docs/sdk/swagger.mdx
=> Documentation of OpenAI function calling schemas generator.

website/package-lock.json, website/package.json
In the JSON schema definition, it is nonsensible to inserting null value to enum property array.
However, Github OpenAPI document is actually doing the crazy thing.
This PR supports it by allowing the null value to the enum proeprty array.
=> Adjust samchon/openapi#40 update to editor.

.github/dependabot.yml, packages/cli/package.json, packages/cli/src/NestiaSetupWizard.ts, packages/cli/src/index.ts, packages/cli/src/internal/ArgumentParser.ts, packages/cli/src/internal/PackageManager.ts
Contributed feature by @ryoppippi from `typia` to here `nestia`.
=> Package manager detection like samchon/typia#1245.

test/features/clone-type-create-duplicate/nestia.config.ts, test/features/clone-type-create-duplicate/src/Backend.ts, test/features/clone-type-create-duplicate/src/controller/auth.controller.ts, test/features/clone-type-create-duplicate/src/controller/users.controller.ts, test/features/clone-type-create-duplicate/src/dto/auth.interface.ts, test/features/clone-type-create-duplicate/src/dto/exception.interface.ts, test/features/clone-type-create-duplicate/src/dto/user.interface.ts, test/features/clone-type-create-duplicate/src/test/features/test.ts, test/features/clone-type-create-duplicate/src/test/index.ts, test/features/clone-type-create-duplicate/tsconfig.json
This PR cannot pass the tests because it includes test cases for the current bug in Nestia.
=> Test: Add `clone type create duplicate` test case

packages/sdk/src/NestiaSdkApplication.ts
fix typo in NestiaSdkApplication.
=> Fix #1072 - fix typo "soure" to "source" in NestiaSdkApplication

benchmark/package.json, package.json, packages/benchmark/package.json, packages/core/package.json, packages/e2e/package.json, packages/editor/package.json, packages/fetcher/package.json, packages/migrate/package.json, packages/sdk/package.json, test/features/distribute-assert-json/packages/api/package.json, test/features/distribute-assert/packages/api/package.json, test/features/distribute-json/packages/api/package.json, test/features/distribute/packages/api/package.json, test/package.json
Minor update by dependency libraries.
=> Upgrade `typia` and `@samchon/openapi`

website/pages/docs/setup.mdx
=> Update setup.mdx - removed stale project

README.md, website/pages/docs/index.mdx, website/theme.config.tsx
This pull request includes updates to various files to correct the Discord link and improve code formatting. The most important changes include updating the Discord badge URL in the `README.md` and `website/pages/docs/index.mdx`, and reformatting the code in `website/theme.config.tsx` for consistency.
Updates to Discord link:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L9-R9): Updated the Discord badge URL to the new link.
* [`website/pages/docs/index.mdx`](diffhunk://#diff-40599ca0c014adddd03e121c88203066eb27b33d4722f580769ceb026a3ac6d5L37-R38): Updated the Discord badge URL to the new link.
Code formatting improvements:
* [`website/theme.config.tsx`](diffhunk://#diff-9ac5cbc4c0593dbcbd24c6c03deff13dbf124e86c567f172c8e236f4750f6bf8L1-R4 …
=> Close samchon/typia#1366: discord server

benchmark/package.json, package.json, packages/benchmark/package.json, packages/cli/package.json, packages/cli/src/internal/ArgumentParser.ts, packages/core/package.json, packages/e2e/package.json, packages/editor/package.json, packages/fetcher/package.json, packages/migrate/package.json, packages/sdk/package.json, test/features/clone-and-propagate/src/Backend.ts, test/features/clone-and-propagate/src/test/features/api/automated/test_api_arrayRecursive_store.ts, test/features/clone-and-propagate/src/test/index.ts, test/features/distribute-assert-json/packages/api/package.json, test/features/distribute-assert/packages/api/package.json, test/features/distribute-json/packages/api/package.json, test/features/distribute/packages/api/package.json, test/package.json, website/package.json
This pull request includes various updates to package versions across multiple files. The most important changes involve updating the `typescript` and `typia` dependencies, as well as some other related package versions.
Dependency updates:
* Updated `typescript` from `~5.6.3` to `~5.7.2` in multiple `package.json` files. [[1]](diffhunk://#diff-ebd18337ce8dc8b96a8403d2731d05bbb7502293037672a62faa622e36d2821aL56-R56) [[2]](diffhunk://#diff-03d34ead8faa24fcf5b6d74b52eaf57db4400f375b60698e3f5024e28b29b0e1L35-R37) [[3]](diffhunk://#diff-6e2e2a1851648938b325ba84de634407a4e69a644ea61102df15ca4a8a7a9758L45-R45) [[4]](diffhunk://#diff-0b810c38f3c138a3d5e44854edefd5eb966617ca84e62f06511f60acc40546c7L83-R83) [[5]](diffhunk://#diff-67adead8de9872bd465961c6570bce9bc06e7164ea116e45ad405ddf8eff238aL42-R …
=> Complete samchon/typia#1415: support TS 5.7

README.md
Been using NestJS on and off for years now, and just stumbling upon this awesome package for the first time. Thanks so much for your effort!
Just a slight change with the grammar in the README.
=> [README] Fixed grammar issue

website/pages/docs/swagger/chat.mdx
This pull request includes updates to the `website/pages/docs/swagger/chat.mdx` file to improve the documentation for the Super A.I. Chatbot. The most important changes include commenting out the preface section, updating the demonstration section title, and adding a detailed explanation of the chatbot's functionality.
Documentation improvements:
* Commented out the preface section to potentially remove it from the rendered documentation.
* Updated the title of the demonstration section to "Super A.I. Chatbot" for better clarity.
* Added a detailed explanation of the chatbot's functionality, including how it selects and calls API functions based on the swagger document.
=> Update `chat.mdx,` change preface section.

website/pages/docs/swagger/strategy.mdx
Full content of the strategy of the swagger documentation.
=> Write swagger documentation strategy

README.md, packages/agent/README.md, packages/benchmark/README.md, packages/chat/README.md, packages/cli/README.md, packages/core/README.md, packages/e2e/README.md, packages/fetcher/README.md, packages/migrate/README.md, packages/sdk/README.md, website/pages/_meta.js, website/pages/docs/index.mdx
This pull request includes updates to the `README.md` files across multiple packages to add a new badge for Gurubase and a minor change to the website metadata and documentation. 
Updates to `README.md` files:
* Added Gurubase badge to `README.md` files in the following packages: `agent`, `benchmark`, `chat`, `cli`, `core`, `e2e`, `fetcher`, `migrate`, and `sdk`.
Website updates:
* Changed the title of the A.I. Chatbot section in `website/pages/_meta.js` from "📦 A.I. Chatbot" to "🤖 A.I. Chatbot".
* Added Gurubase badge information to the documentation index in `website/pages/docs/index.mdx`.
=> Add gurubase chatbot

README.md, website/pages/_meta.js, website/pages/docs/index.mdx, website/pages/docs/swagger/_meta.js, website/pages/docs/swagger/chat.mdx, website/src/movies/home/HomeHeroMovie.tsx
This pull request includes several updates to improve the documentation and user interface of the Nestia project. The most important changes involve updating references to the Gurubase chatbot and modifying the titles and icons in the documentation pages.
Documentation updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L8-R9): Updated the badge labels for Guide Documents and Gurubase to "Guide Documents" and "Document Chatbot" respectively.
User interface improvements:
* [`website/pages/_meta.js`](diffhunk://#diff-54bc2d530749150030c3c846b56e6da49ed548e3523d5462ad8bd32ca608958dR14-R19): Added a new entry for Gurubase with the title "Document Chatbot" and configured it to open in a new window.
* …
=> Gurubase as main doc

packages/cli/package.json, packages/cli/src/internal/PluginConfigurator.ts, website/pages/_app.js, website/pages/_meta.js, website/src/movies/home/HomeHeroMovie.tsx
This pull request includes several changes across different files to update dependencies, modify configurations, and remove a feature. The most important changes include updating the version in `package.json`, modifying the validation method in `PluginConfigurator`, adding a new script in `_app.js`, and removing the GuruBase chatbot feature from multiple files.
Version update:
* [`packages/cli/package.json`](diffhunk://#diff-6e2e2a1851648938b325ba84de634407a4e69a644ea61102df15ca4a8a7a9758L3-R3): Updated the version from `6.3.1` to `6.4.0`.
Configuration changes:
* [`packages/cli/src/internal/PluginConfigurator.ts`](diffhunk://#diff-aa46d2a23bb027483d626bacfc2d131d9fdd4e124134b42e30ab0c5de3a25eb2L88-R88): Changed the validation method from "assert" to "validate".
Script addition:
* …
=> Add gurubase widget

packages/e2e/package.json, packages/e2e/src/DynamicExecutor.ts
This pull request includes updates to the `packages/e2e` package to enhance functionality and fix issues. The most important changes involve updating the package version, adding a new property to the `DynamicExecutor` namespace, and modifying the function execution logic for better handling of return values.
Version update:
* [`packages/e2e/package.json`](diffhunk://#diff-67adead8de9872bd465961c6570bce9bc06e7164ea116e45ad405ddf8eff238aL3-R3): Updated the version from `0.8.0` to `0.8.2`.
Enhancements to `DynamicExecutor`:
* [`packages/e2e/src/DynamicExecutor.ts`](diffhunk://#diff-b0df7fe1fe55993907695fe0a83790aebea7ae1505d17ad0397178b133a9fd47R148-R152): Added a new `value` property to store the returned value from the function.
* …
=> Trace return value of testing function

website/pages/docs/swagger/chat.mdx
This pull request includes significant additions to the `website/pages/docs/swagger/chat.mdx` file, focusing on providing a comprehensive guide for setting up a backend development environment with `@agentica` for AI chatbot services. The key changes include instructions for package installation, server setup, and API controller definition.
Backend Development Guide:
* Added a new section titled "Backend Development" with subsections for setup, bootstrap, and API controller.
* Provided installation commands for necessary packages: `@agentica/core`, `@agentica/rpc`, `@samchon/openapi`, and `tgrid`.
* Included instructions to upgrade the NestJS application for WebSocket compatibility using `WebSocketAdaptor.upgrade()`.
* Added an example of defining a WebSocket route in a controller to …
=> Backend development of AI chatbot page

package.json, packages/migrate/src/analyzers/MigrateControllerAnalyzer.ts, packages/migrate/src/executable/bundle.js, packages/migrate/src/programmers/MigrateApiNamespaceProgrammer.ts, pnpm-lock.yaml
This pull request includes several updates and improvements across multiple files, focusing on dependency upgrades, bug fixes, and code quality improvements. The most significant changes involve updating dependencies in `pnpm-lock.yaml`, fixing route path handling in `MigrateApiNamespaceProgrammer.ts`, and improving code clarity in `MigrateControllerAnalyzer.ts`.
* Upgraded `@nestjs/common`, `@nestjs/core`, `@nestjs/platform-express`, `@nestjs/platform-fastify`, and `@nestjs/swagger` to version `11.1.0` or higher for improved compatibility and features. [[1]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL692-R705) [[2]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL1358-R1359) …
=> Fix `@nestia/migrate` bug from invalid path

package.json, packages/benchmark/package.json, packages/core/package.json, packages/e2e/package.json, packages/editor/package.json, packages/fetcher/package.json, packages/migrate/package.json, packages/migrate/src/analyzers/NestiaMigrateControllerAnalyzer.ts, packages/migrate/src/programmers/NestiaMigrateApiProgrammer.ts, packages/migrate/src/test/index.ts, packages/sdk/package.json
This pull request primarily updates the version numbers across multiple `package.json` files to reflect a new development version (`7.0.0-dev.20250608`) and introduces improvements to file path validation and error handling in the `@nestia/migrate` package. These changes ensure consistency across the project and enhance the robustness of the migration process.
* Updated the version number in `package.json` files for the following packages: `@nestia/station`, `@nestia/benchmark`, `@nestia/core`, `@nestia/e2e`, `@nestia/editor`, `@nestia/fetcher`, `@nestia/migrate`, and `@nestia/sdk`. This includes adjustments to `peerDependencies` where applicable. [[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L4-R4) …
=> fix(migrate): invalid path pattern `//`

README.md, package.json, packages/e2e/src/ArrayUtil.ts, packages/e2e/src/GaffComparator.ts, packages/e2e/src/RandomGenerator.ts, packages/e2e/src/TestValidator.ts
This pull request introduces several enhancements and updates across multiple files, focusing on documentation improvements, feature additions, and version updates. The most significant changes include adding detailed examples and descriptions for utility functions and comparator methods, introducing a new library in the README, and updating the package version.
* Expanded documentation for all utility functions, including `asyncFilter`, `asyncForEach`, `asyncMap`, `asyncRepeat`, `has`, `repeat`, and `subsets`. Each function now includes detailed descriptions, type annotations, and usage examples to improve clarity and usability. [[1]](diffhunk://#diff-ebd548ce03e42567bc51c7452b7da7a9e121119f2464402e1c68b2523d7ccfa9L2-R51) F3aa3444L21R22, …
=> e2e description comments for AI few shot

package.json, packages/e2e/src/TestValidator.ts, packages/e2e/src/internal/json_equal_to.ts
New function `TestValidator.notEquals()`, and make `TestValidator.equals()`'s `y` parameter to be nullable and undefindable for AI generation.
------------------
This pull request introduces a version bump for the package, enhances the `TestValidator` utility with a new method, and updates type handling in JSON comparison functions to support `null` and `undefined` values. Below are the key changes:
* Updated the package version in `package.json` from `7.0.1` to `7.0.2` to reflect the new changes.
* Added a new `notEquals` method in `TestValidator` to validate deep inequality between two values using JSON comparison. This method includes an optional exception filter and detailed documentation with examples.
* Modified the `equals` method in `TestValidator` to accept `T | null | undefined` …
=> `TestValidator.notEquals()`.

deploy/index.js, packages/benchmark/README.md, packages/benchmark/package.json, packages/cli/README.md, packages/cli/package.json, packages/core/README.md, packages/core/package.json, packages/e2e/README.md, packages/e2e/package.json, packages/fetcher/README.md, packages/fetcher/package.json, packages/migrate/src/NestiaMigrateApplication.ts, packages/migrate/src/executable/bundle.js, packages/sdk/README.md, packages/sdk/package.json
This pull request introduces several updates across multiple packages in the `Nestia` project, including version bumps, dependency adjustments, and documentation enhancements. Additionally, it adds a new feature to the migration tool and updates the `deploy/index.js` script to include a new package.
* Updated the version of all affected packages (`@nestia/benchmark`, `@nestia/core`, `@nestia/e2e`, `@nestia/fetcher`, `@nestia/sdk`, and `nestia`) to `7.1.1-dev.20250714`. This includes aligning peer dependencies to the new version where applicable. (`[[1]](diffhunk://#diff-03d34ead8faa24fcf5b6d74b52eaf57db4400f375b60698e3f5024e28b29b0e1L3-R3)`, `[[2]](diffhunk://#diff-6e2e2a1851648938b325ba84de634407a4e69a644ea61102df15ca4a8a7a9758L3-R3)`, …
=> Fix `@nestia/migrate`'s `nestia.config.ts` file to follow keyword option.

package.json, packages/migrate/src/NestiaMigrateApplication.ts, packages/migrate/src/executable/NestiaMigrateCommander.ts, packages/migrate/src/programmers/NestiaMigrateNestMethodProgrammer.ts, packages/migrate/src/structures/INestiaMigrateConfig.ts
This pull request introduces multiple changes across the codebase, primarily focusing on refactoring and enhancements to improve maintainability and functionality. Key updates include the addition of new utility functions, deprecation of methods, and modifications to existing logic for better abstraction and clarity.
- **Utility Function Addition**: Added a new `renameSlug` function in `packages/migrate/src/NestiaMigrateApplication.ts` to replace the inline renaming logic previously implemented in the `rename` method. The `rename` method was removed, and all references to it were updated to use `renameSlug`. [[1]](diffhunk://#diff-0a5ce7730972391752dacee1705655af2b015a121715381435acb11a2925bd0dL96-R103) [[2]](diffhunk://#diff-0a5ce7730972391752dacee1705655af2b015a121715381435acb11a2925bd0d …
=> `INestiaMigrateConfig.programmer` for customization of code generation.

website/src/constants/EDITOR_EXAMPLES.ts
```bash
pnpm install
npm run build
npm run test
```
=> fix broken urls
